schema/chat_messages.go
schema/chat_messages_test.go
schema/doc.go
schema/documents.go
schema/retrivers.go
schema/schema.go

This adds the start of our schema package, based on the typescript and python implementations of langchain.
Fixes #24
References:
* https://github.com/hwchase17/langchainjs/blob/main/langchain/src/schema/index.ts
* https://github.com/hwchase17/langchain/blob/master/langchain/schema.py
PR Checklist

schema: Add schema package

---

schema/language_model.go
schema/memory.go
schema/prompts.go

This fleshes out more of the schema package.

schema: add more upstream schema concepts

---

.golangci.yaml

Changes:
- Disabled `testpackage` linter

lint: disable testpackage

---

.github/workflows/lint-build-test.yaml

Improved:
- GitHub Actions would only be triggered when new commits has been pushed to branches within this repository when `on: push` has been set

ci: trigger lint-build-test GitHub Actions within PRs

---

examples/huggingface-llm-example/huggingface_example.go
examples/local-llm-example/local_llm_example.go
examples/openai-completion-example/openai_completion_example.go
exp/agent/executor/agent_executor.go
exp/agent/mrkl/mrkl.go
exp/chains/chains.go
exp/chains/llm_chain.go
exp/chains/llm_chain_test.go
exp/chains/retrival_qa_chain.go
exp/chains/stuff_documents_chain.go
exp/chains/stuff_documents_chain_test.go
llms/huggingface/huggingfacellm.go
llms/llms.go
llms/local/localllm.go
llms/openai/openaillm.go

This propagates context.Context. Fixes #65 
contributor.

context: add context throughout

---

exp/agent/mrkl/mrkl.go
exp/agent/mrkl/prompt.go
prompts/prompt_template.go
prompts/templates.go

contributor.
Got the MRKL agent in a working state.
- Fixed broken template rendering
- Cleaned up the main prompt
- Added various error handling
- Various code cleanup
- Added action sanitization because sometimes the LLM will select `Google` even if you told it the tool's name was `google`

Make the MRKL agent functional

---

docs/parity_matrix.md

Add a docs folder with the parity matrix md file from  #61

docs: add docs folder and parity matrix md file

---

examples/huggingface-llm-example/huggingface_example.go
examples/local-llm-example/local_llm_example.go
examples/openai-completion-example/openai_completion_example.go
exp/chains/llm_chain.go
llms/huggingface/huggingfacellm.go
llms/llms.go
llms/local/localllm.go
llms/openai/openaillm.go
llms/options.go

This refactors how options are provided to llms.
Addresses #64

llms: Options refactor

---

chains/chain.go
chains/llm.go
chains/llm_test.go

This fixes a few small issues from #70

chains: Fix call and improve errors

---

.github/workflows/ci.yaml
chains/chain.go
chains/llm.go
chains/llm_test.go
examples/openai-chat-example/openai_chat_example.go
llms/openai/internal/openaiclient/chat.go
llms/openai/internal/openaiclient/openaiclient.go
llms/openai/openaillm.go
llms/options.go

This enhances the chat completion capabilities of the openai client.
contributor.

llms: Enhance chat completion capabilities in openai implementation

---

chains/chains.go
chains/errors.go
chains/llm.go
chains/prompt_selector.go
chains/question_answering.go
chains/retrival_qa.go
chains/retrival_qa_test.go
chains/stuff_documents.go
chains/stuff_documents_test.go

- Add "StuffDocuments" chain 
https://github.com/hwchase17/langchain/blob/master/langchain/chains/combine_documents/stuff.py
https://github.com/hwchase17/langchainjs/blob/main/langchain/src/chains/combine_docs_chain.ts
- Add "RetrievalQA" chain
https://github.com/hwchase17/langchainjs/blob/main/langchain/src/chains/retrieval_qa.ts
https://github.com/hwchase17/langchain/blob/master/langchain/chains/retrieval_qa/base.py
- Add "PromptSelector" interface and "ConditionalPromptSelector"
https://github.com/hwchase17/langchainjs/blob/main/langchain/src/chains/prompt_selector.ts
https://github.com/hwchase17/langchain/blob/master/langchain/chains/prompt_selector.py

chains: add retrieval QA, stuff documents and prompt selector

---

chains/chains.go
llms/llms.go
llms/openai/internal/openaiclient/chat.go
llms/openai/openaillm.go

This defines a ChatLLM interface that exposes a typed interface to chat models.

llms: Add ChatLLM type

---

examples/huggingface-llm-example/huggingface_example.go
llms/huggingface/huggingfacellm.go
llms/options.go

---
Phew, your questionnaire is quite complex, feels like I'm taking exams :)
Here's a brief description of this PR. It allows the use of HuggingFace pipelines by specifying a custom repository instead of hardcoded "google/flan-t5-xl" (which not work btw). For my tests, I used the GPT-2 model, but any other model can be used if desired.
I implemented the mentioned setting through `llms.WithModel` and demonstrated its usage in the corresponding example. I'm sure this will help newcomers like me to understand how to use this library more quickly.
Thank you guys for this amazing extension! I've trying to integrate executing of Python scripts to LocalAI and you saved a lot of my time.
PS. Idk how to test it correctly, al lot of existing tests don't check similar thing, so maybe you may help …

Improving HuggingfaceLLM: Configurable RepoID option

---

examples/openai-chat-example/openai_chat_example.go
llms/openai/internal/openaiclient/chat.go
llms/openai/openaillm.go
llms/options.go
llms/vertexai/vertexai_palm_llm.go

llms: AddWithStreamingFunc

---

examples/huggingface-llm-example/huggingface_example.go
llms/huggingface/huggingfacellm.go

---
Hello! This PR contains a default model "gpt2" for HuggingFace LLM ([details here](https://github.com/tmc/langchaingo/pull/109#pullrequestreview-1450108073))

`gpt2` used as default model of huggingface package

---

llms/openai/internal/openaiclient/chat.go
llms/openai/internal/openaiclient/completions.go
llms/openai/internal/openaiclient/embeddings.go
llms/openai/internal/openaiclient/openaiclient.go
llms/openai/openaillm.go
llms/openai/openaillm_option.go

llm-openai-client: openai base url option

---

examples/huggingface-llm-example/huggingface_example.go
llms/huggingface/huggingfacellm.go
llms/huggingface/huggingfacellm_option.go
llms/huggingface/internal/huggingfaceclient/huggingfaceclient.go
llms/huggingface/internal/huggingfaceclient/inference.go
llms/options.go

---
Greetings,
This pull request encompasses numerous enhancements concerning global options, as outlined in issue #112. In essence, it introduces several variables to the `llms.CallOptions` struct, namely:
* TopP
* TopK
* Seed
* MinLength
* MaxLength
* RepetitionPenalty
Additionally, it introduces related functions for changing options above such as WithTopK, WithTopP, WithRepetitionPenalty, and so on.
All of the aforementioned options have been utilized in the HuggingFace client with help of omitempty.
Furthermore, this PR includes supplementary modifications to the HuggingFace client, enabling the initialization of the client without requiring the presence of `HUGGINGFACEHUB_API_TOKEN` in the environment (see huggingface_options.go).
Please let me know if you require any further …

feat: Options like WithSeed, WithTopK and so on

---

docs/parity_matrix.md
documentloaders/csv.go
documentloaders/csv_test.go
documentloaders/testdata/test.csv
textsplitter/recursive_character_test.go

Add initial implementation for a CSV loader.
Python reference: https://github.com/hwchase17/langchain/blob/master/langchain/document_loaders/csv_loader.py

document loaders: add csv loader

---

embeddings/doc.go
exp/doc.go
llms/doc.go
llms/llms.go
memory/doc.go
outputparser/doc.go
textsplitter/doc.go
vectorstores/doc.go

docs: added package level comments to codebase

---

agents/conversational.go
agents/conversational_prompt.go
agents/initialize.go
agents/options.go

Add conversational agent, you can reference https://python.langchain.com/docs/modules/agents/agent_types/chat_conversation_agent.

agents: add conversational agent

---

tools/serpapi/internal/client.go
tools/wikipedia/client.go
tools/wikipedia/doc.go
tools/wikipedia/wikipedia.go
tools/wikipedia/wikipedia_test.go

This adds the wikipedia tool.
https://github.com/hwchase17/langchain/blob/master/langchain/tools/wikipedia/tool.py

tools: add wikipedia

---

agents/conversational_prompt.go
agents/executor.go
agents/initialize.go
agents/options.go
examples/mrkl-agent-example/go.mod

This makes the max iterations functional  and sets all tool names upper case in the in the executor. An option for returning Intermediate steps is also added.

agents: fix bug and add option for returning steps

---

chains/api.go
chains/api_test.go

chains: add api chain

---

.github/workflows/ci.yaml
Makefile

Add a new CI step and Makefile entry (`build-examples`) to validate if examples are building.
Demo: https://github.com/tmc/langchaingo/actions/runs/5379426518/jobs/9760632495

CI: Add ci step and Makefile entry to ensure examples are healthy

---

agents/conversational.go
agents/conversational_prompt.go
agents/conversational_test.go
agents/executor.go
agents/markl_test.go
agents/mrkl.go
agents/options.go

agents: add memory to executor and add test for conversational

---

README.md
examples/sql-database-chain-example/go.mod
examples/sql-database-chain-example/go.sum

docs: fix readme example and update sql example dependencies

---

textsplitter/token_splitter.go
textsplitter/token_splitter_test.go

add new token splitter

---

examples/document-qa-example/document_qa.go

This will be my first ever open source contribution. I have seen other areas in which I can help with this project -- including the sql_chain package, but I hope this very simple PR that fixes typo will help me understand how contributing works and encourages me to do so much more. Thank you.

examples: fixed typos in document-qa-example

---

embeddings/openai.go
embeddings/openai_test.go
embeddings/options.go

- adding ability to pass in the embedding options when creting the OpenAI embedder
- this resolves issue: https://github.com/tmc/langchaingo/issues/159

feat: Embeddings - extending the create method to accept options

---

tools/duckduckgo/ddg.go
tools/duckduckgo/internal/client.go

#169 tools/ddg, follow up:
- add documentation for exported functions and types
- move DefaultUserAgent variable out of internal package
- don't set user-agent header if the value is empty
- lint: add a newRequest method to reduce complexity of Search method

docs(tools/ddg): documentation and api improvements

---

docs/parity_matrix.md
outputparser/regex_parser.go
outputparser/regex_parser_test.go

This is a necessary component for use in the map rerank chain.
Changes:
- Adds regex parser with tests.
- Minor nits on docs.

feat: regex parser

---

llms/openai/internal/openaiclient/chat.go
llms/openai/internal/openaiclient/completions.go
llms/openai/internal/openaiclient/embeddings.go
llms/openai/internal/openaiclient/openaiclient.go
llms/openai/openaillm.go
llms/openai/openaillm_option.go

This PR adds the support for openai organzations.
Without this it's only possible to use the default organization of an account.
[Python Implementation](https://github.com/hwchase17/langchain/blob/master/langchain/llms/openai.py#L230)
As for the tests, I don't know if it's necessary since it's only adding a header to the openAI request and llms/openai doesn't seems to contain tests anyway

openaillm: add support for openai organizations

---

chains/transform.go
chains/transform_test.go

This adds the transform chain. https://github.com/hwchase17/langchain/blob/master/langchain/chains/transform.py

chains: add transform chain

---

llms/openai/internal/openaiclient/openaiclient.go

do not overwrite the model passed in by dynamic runtime requests with client init

llms: fix request model overrided by client model

---

chains/sequential.go
chains/sequential_test.go
docs/parity_matrix.md

* Allow clients to specify `Memory` implementations to use with sequential chains

chains: add memory support for sequential chain

---

llms/openai/internal/openaiclient/chat.go
llms/openai/internal/openaiclient/embeddings.go
llms/openai/internal/openaiclient/openaiclient.go
llms/openai/openaillm.go
llms/openai/openaillm_option.go

For issue #206 add WithHTTPClient option for OpenAI.

openai: added WithHTTPClient option

---

documentloaders/csv.go
documentloaders/csv_test.go

- fixing the compile error when we want to use the lib outside of the repo (screenshot)
- adding test

documentloader/csv: Fixing issue with CSV document loader

---

chains/chains.go
chains/conversational_retrieval_qa.go
chains/sequential.go
memory/buffer.go
memory/buffer_test.go
memory/chat.go
memory/chat_test.go
memory/simple.go
memory/token_buffer.go
memory/token_buffer_test.go
schema/chat_message_history.go
schema/memory.go

Support give context for memory #248

memory: support call with context 

---

llms/openai/openaillm_chat.go

role assistant message maybe have function_call

bug: role assistant message maybe have function_call

---

llms/openai/openaillm_option.go
memory/buffer.go
memory/buffer_test.go
memory/chat.go
memory/simple.go
memory/token_buffer.go
schema/chat_message_history.go
schema/memory.go

- when adding context the `Clear` method was missed https://github.com/tmc/langchaingo/pull/249, this PR aligns with everything in the chat history schema

schema/chat-history: Chat history clear method context

---

embeddings/ernie/ernie.go
embeddings/ernie/options.go
examples/ernie-completion-example/ernie_completion_example.go
llms/ernie/doc.go
llms/ernie/erniellm.go
llms/ernie/erniellm_option.go
llms/ernie/internal/ernieclient/ernieclient.go

- [*] Read the [Contributing documentation](https://github.com/tmc/langchaingo/blob/main/CONTRIBUTING.md).
- [*] Read the [Code of conduct documentation](https://github.com/tmc/langchaingo/blob/main/CODE_OF_CONDUCT.md).
- [*] Name your Pull Request title clearly, concisely, and prefixed with the name of the primarily affected package you changed according to [Good commit messages](https://go.dev/doc/contribute#commit_messages) (such as `memory: add interfaces for X, Y` or `util: add whizzbang helpers`).
- [*] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [*] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `Fixes #123`).
- [*] Describes the source of new …

feat: add Baidu LLM ERNIE

---

README.md

Added resources section

---

llms/openai/internal/openaiclient/chat.go
llms/openai/internal/openaiclient/completions.go
llms/openai/internal/openaiclient/openaiclient.go
llms/openai/openaillm.go
llms/openai/openaillm_chat.go

Fixes https://github.com/tmc/langchaingo/pull/266 and https://github.com/tmc/langchaingo/issues/232

openai: Use chat completions for normal completions (as recommended)

---

jsonschema/json.go
jsonschema/json_test.go

This pulls in jsonschema for now, until we incorporate #145

Add jsonschema

---

docs/docs/index.md
docs/docusaurus.config.js
llms/openai/internal/openaiclient/chat.go
llms/openai/internal/openaiclient/completions.go
llms/openai/internal/openaiclient/openaiclient.go
llms/openai/openaillm.go
llms/openai/openaillm_chat.go
schema/chat_messages.go

This sends partial function call results when streaming with function calls.

Function call streaming

---

chains/options.go

add chain call option: WithTopP

---

chains/stuff_documents.go
chains/stuff_documents_test.go

For Issue: https://github.com/tmc/langchaingo/issues/285

remove last separator

---

llms/vertexai/vertexai_palm_llm_chat.go

vertexai chat-bison parameters has an optional context prompt. added system message to be the context in the request
in langchain > vertexai.py SystemMessage type is being set as context prompt:

add context prompt in vertexai chat

---

callbacks/callbacks.go
callbacks/log.go
vectorstores/vectorstores.go

- adding query param to the `HandleRetrieverEnd`, so that we are able to connect if needed what documents are returned for what query on the retriever
- fixing typo

callback-handler: Callback handler for `HandleRetrieverEnd`

---

llms/vertexai/internal/vertexaiclient/palm_client.go

- VertexAI embeddings are returning f64, but we are expecting f32 https://github.com/tmc/langchaingo/pull/297 this PR caused the issue.
- for not I'm just parsing it to f64, not sure if we should revert https://github.com/tmc/langchaingo/pull/297 or contintue like this.

vertexai/embeddings: Fix VertexAI embeddings

---

llms/ernie/erniellm.go
llms/ernie/internal/ernieclient/ernieclient.go

- [*] Read the [Contributing documentation](https://github.com/tmc/langchaingo/blob/main/CONTRIBUTING.md).
- [*] Read the [Code of conduct documentation](https://github.com/tmc/langchaingo/blob/main/CODE_OF_CONDUCT.md).
- [*] Name your Pull Request title clearly, concisely, and prefixed with the name of the primarily affected package you changed according to [Good commit messages](https://go.dev/doc/contribute#commit_messages) (such as `memory: add interfaces for X, Y` or `util: add whizzbang helpers`).
- [*] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [*] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `Fixes #123`).
- [*] Describes the source of new …

fix: model selection and throwing exceptions

---

llms/vertexai/internal/vertexaiclient/palm_client.go

Sorry, StopSequence wasn't added to the map yet.

Adding []interface{} to mergedParams array for VertexAI

---

schema/documents.go
vectorstores/pinecone/restapi.go

- Add `Score` attribute to `schema.Document` to allow vector searches to return specific similarity score
- Update `pinecone.restQuery` to return score value as part of  the `schema.Document` return type

schema: add score attribute to document type to allow similarity score to be returned from vector search

---

examples/chroma-vectorstore-example/chroma_vectorstore_example.go
vectorstores/chroma/chroma.go
vectorstores/chroma/chroma_test.go
vectorstores/chroma/options.go

vectorstore: openai apikey is must required only when embedder is nil

---

.github/workflows/publish-docs.yaml
docs/Makefile
docs/docs/getting-started/guide-chat.mdx
docs/docs/getting-started/guide-ollama.mdx
docs/docs/getting-started/guide-openai.mdx
docs/docs/index.md
docs/docs/modules/agents/index.mdx
docs/docs/modules/chains/index.mdx
docs/docs/modules/chains/llm_chain.mdx
docs/docs/modules/data_connection/document_loaders/index.mdx
docs/docs/modules/data_connection/index.mdx
docs/docs/modules/data_connection/vector_stores/index.mdx
docs/docs/modules/memory/index.mdx
docs/docs/modules/model_io/index.mdx
docs/docusaurus.config.js

This adds docs deploy infra and adds an Ollama quickstart guide.

docs: Add docs publishing, include Ollama quickstart guide.

---

examples/openai-gpt4-turbo-example/go.mod
examples/openai-gpt4-turbo-example/go.sum
examples/openai-gpt4-turbo-example/openai_gpt4_turbo.go

examples: Add gpt4 turbo example

---

tools/serpapi/internal/client.go

Fix [#323](https://github.com/tmc/langchaingo/issues/323)

serpapi: remove unnecessary replacement from url

---

embeddings/ollama/ollama.go
embeddings/ollama/ollamachat/ollama_chat.go

Applies the refactored code in #357 to remove duplicated code here.
Updates #356

embeddings: use EmbedderClient for ollama embeddings

---

embeddings/openai/openai.go
embeddings/openai/openaichat/openai_chat.go

Applies the refactored code in #357 to remove duplicated code here.
Updates #356

embeddings: use EmbedderClient for openai embeddings

---

embeddings/ernie/ernie.go

also removes unused internal method
For #356

embeddings: use EmbedderClient for ernie embeddings

---

examples/huggingface-milvus-vectorstore-example/README.md
examples/huggingface-milvus-vectorstore-example/docker-compose.yml
examples/huggingface-milvus-vectorstore-example/milvus_vectorstore_example.go

adding huggingface TEI router as docker service for convenience. 
Follow up to #352

Simplify milvus example 

---

examples/pinecone-vectorstore-example/go.mod
examples/pinecone-vectorstore-example/go.sum
examples/pinecone-vectorstore-example/pinecone_vectorstore_example.go

Now that the main module's version was bumped, update the example to use a proper embedder
For #379

examples/pinecone-vectorstore-example: use new embedder

---

embeddings/doc.go
embeddings/example_test.go

embeddings: add example of proper usage, and tweak doc.go accordingly

---

.github/workflows/publish-docs.yaml

Fix errors like https://github.com/tmc/langchaingo/actions/runs/7094309081

workflow: fix publish-docs workflow error

---

llms/openai/openaillm_chat.go

Based on the example of [openai function calling](https://openai.com/blog/function-calling-and-other-api-updates#:~:text=call%20your%20API-,Step%203,-%C2%B7), currently the content of the function call in `schema.AIChatMessage` is being omitted.

openai message: support function call in client messages

---

llms/ernie/erniellm.go
llms/ernie/erniellm_option.go

Integrate ERNIE-Bot-8K model into the project.  ERNIE-Bot-8K is a newly released model by Ernie.
The official documentation can be found at the following link: 
https://cloud.baidu.com/doc/WENXINWORKSHOP/s/6lp69is2a

LLM: Integration of ERNIE-Bot-8K Model

---

examples/chroma-vectorstore-example/chroma_vectorstore_example.go
examples/ernie-chat-example/ernie_chat_example.go
examples/ernie-completion-example/ernie_completion_example.go
examples/ernie-function-call-example/ernie_function_call_example.go
examples/ernie-function-call-streaming-example/ernie_function_call_example.go
examples/ollama-chroma-vectorstore-example/chroma_vectorstore_example.go
llms/ollama/internal/ollamaclient/ollamaclient.go
llms/ollama/internal/ollamaclient/types.go
llms/ollama/ollamallm_chat.go

ollama: Add use of new chat endpoint

---

chains/api_test.go

test: fix api chain test error (#414)

---

vectorstores/chroma/chroma.go

vectorstores: fix chroma not return score from SimilaritySearch

---

callbacks/log_stream.go
chains/options.go
examples/llm-chain-example/go.mod
examples/llm-chain-example/llm_chain.go

Feat: use chains callback as streaming func

---

llms/openai/openaillm.go
llms/openai/openaillm_chat.go

fix: avoid panic when call openai.NewChat() and openai.New()

---

llms/llms.go
llms/openai/openaillm_chat.go

I am developing a chat app with langchaingo, and the StopReason field is essential for applications

add StopReason field in Generation struct.

---

vectorstores/weaviate/weaviate.go

vectorstores: fix weaviate not return score from SimilaritySearch

---

callbacks/combining.go

Feat: support combine multi callbacks

---

llms/ollama/ollamallm_chat.go

Fix the problem:
There is no LLMError handle callback in Chat generation process

Fix: Add error handle for Chat Generate

---

agents/executor.go
callbacks/callbacks.go
callbacks/combining.go
callbacks/log.go
callbacks/simple.go
examples/mrkl-agent-example/go.mod

add a HandleAgentFinish callback function to callback Handler interface.

support agent finish callback

---

go.mod
go.sum

Signed-off-by: bjwswang <bjwswang@gmail.com>
Changelogs:
1. Bump chroma-go to latest version which optimizes lots of things. See https://github.com/amikos-tech/chroma-go/pull/4
2. Remove empty file agents/executor

chore: bump chroma-go to latest version

---

llms/openai/openaillm_chat.go

Add GenerationInfo to GenerateContent

---

llms/generatecontent.go
llms/openai/multicontent_test.go
llms/openai/openaillm_chat.go

Add function invocation into GenerateContent responses

---

callbacks/callbacks.go
callbacks/combining.go
callbacks/simple.go
llms/googleai/googleai_llm.go
llms/llms.go
llms/ollama/ollamallm_chat.go
llms/openai/openaillm_chat.go

Add callback handler method for GenerateContent start and end

---

docs/docs/modules/model_io/models/embeddings/index.mdx

* First step on contributing on the documentation site (#144)  by adding example code to corresponding package.

docs: add example to embeddings

---

llms/googleai/googleai_llm.go
llms/googleai/googleai_llm_test.go

googleai: propagate more options and add test

---

memory/window_buffer.go
memory/window_buffer_test.go

memory: fix cutMessages in ConversationWindowBuffer

---

vectorstores/pgvector/pgvector.go
vectorstores/pgvector/pgvector_test.go

vectorstores: Wrapped the PGVector store init function in a single transaction

---

vectorstores/pgvector/pgvector.go

vectorstores: Added a unique constraint for the collection name when using PGVector

---

vectorstores/pgvector/options.go

vectorstores: Added the missing comment on the exported WithCollectionMetadata function

---

vectorstores/pgvector/pgvector.go

---
See this discussion for more details:
https://github.com/tmc/langchaingo/pull/561#discussion_r1468797930

vectorstores: Removed the custom ID option for embeddings when using PGVector

---

callbacks/log.go

Here is a PR for logging using the new introduced method in v0.1.4
I have not yet added tests as there are no existing tests for this package.

Callbacks Log: Implement logging for text types, fixes #596

---

agents/conversational_test.go

agents: improve TestConversationalWithMemory testing

---

examples/openai-completion-example-with-http-debugging/go.mod
examples/openai-completion-example-with-http-debugging/go.sum
examples/openai-completion-example-with-http-debugging/openai_completion_example.go
llms/anthropic/internal/anthropicclient/anthropicclient.go
llms/anthropic/internal/anthropicclient/completions.go
llms/ernie/internal/ernieclient/chat.go
llms/ernie/internal/ernieclient/ernieclient.go
llms/googleai/internal/palmclient/palmclient.go
llms/huggingface/internal/huggingfaceclient/huggingfaceclient.go
llms/huggingface/internal/huggingfaceclient/inference.go
llms/ollama/internal/ollamaclient/types.go
llms/openai/internal/openaiclient/chat.go
llms/openai/internal/openaiclient/completions.go

Fixes #600, adds example dumping http requests to hosted model.

llms: Remove omitempty from temperature params

---

chains/llm_test.go
llms/googleai/googleai.go

This reverts commit 40d40ea18884e09f0108c420d2bbdeb8637a412f.
See #625 and #626

Revert "googleai: fix options need add default value"

---

chains/llm_math.go
examples/llmmath-chain-example/llm_math_chain.go

* Better error message from Starlark eval
* Fix to a sample that actually works

Fix llm_math_chain example

---

docs/docs/modules/model_io/models/llms/Integrations/huggingface.mdx

Add huggingface documentation

---

vectorstores/milvus/options.go

vectorstores/milvus: add WithMetricType

---

examples/chroma-vectorstore-example/chroma_vectorstore_example.go
examples/chroma-vectorstore-example/go.mod
examples/chroma-vectorstore-example/go.sum
go.mod
go.sum
vectorstores/chroma/README.md
vectorstores/chroma/chroma.go
vectorstores/chroma/chroma_test.go
vectorstores/chroma/embedder.go
vectorstores/chroma/options.go

Refs: https://github.com/amikos-tech/chroma-go/releases/tag/v0.1.2

chore: Chroma dependency update

---

examples/openai-function-call-streaming-example/go.mod
llms/openai/internal/openaiclient/chat.go
llms/openai/openaillm_option.go

llms/openai: Optionally supply ResponseFormat

---

agents/conversational.go
agents/executor.go
agents/initialize.go
agents/mrkl.go
agents/openai_functions_agent.go
agents/options.go

Improvements on agents package API

---

httputil/debug_transport.go

httputil: Add httputil package to provide some common helpers

---

examples/openai-completion-example-with-http-debugging/openai_completion_example.go

examples: Fix up import in openai debugging example

---

README.md

readme: Include contributors

---

vectorstores/weaviate/weaviate_test.go

The existing image is no longer published.
Refs #699

vectorstores/weaviate: Update testcontainer image

---

vectorstores/milvus/milvus_test.go

vectorstores/milvus: Update testcontainer image

---

tools/sqldatabase/postgresql/postgresql_test.go

tools/sqldataase: update postgres image

---

tools/sqldatabase/mysql/mysql_test.go

chains: Update mysql testcontainer image

---

vectorstores/qdrant/qdrant_test.go

vectorstores/qdrant: Update testcontainer image 

---

docs/docs/modules/chains/index.mdx

doc: fix typo

---

llms/ollama/internal/ollamaclient/types.go
llms/ollama/ollama_test.go
llms/ollama/ollamallm.go
llms/ollama/options.go

feat(ollama): support 'keep_alive' parameter

---

llms/openai/internal/openaiclient/chat.go

Fixes bug described in: #370 .

Fix OpenAI createChat bug

---

llms/bedrock/bedrockllm_test.go
llms/bedrock/models_list.go

AWS announced that Meta’s Llama 3 models are now available in [Amazon Bedrock](https://aws.amazon.com/blogs/aws/metas-llama-3-models-are-now-available-in-amazon-bedrock/).

llms: add llama3 models to bedrock

---

llms/googleai/googleai.go

feat: support gemini pro system prompt

---

tools/scraper/scraper.go

When running the scraper, there would occasionally be panics for concurrent map access of the `scrapedLinks` map.  
Adding a `sync.RWMutex` around all accesses of the map fixes this issue.

scraper: fix concurrent scraped links map access

---

llms/ernie/erniellm.go
llms/ernie/erniellm_option.go

The ERNIE-Bot-8K was decommissioned on April 12, 2024. If anyone wishes to continue using this service, please switch to ERNIE-3.5-8K

LLM: Remove ERNIE-Bot-8K Model

---

llms/googleai/option.go

Added methods to options that was not implemented yet
Some of the methods for the options struct was not implemented yet, so I added them.
WithDefaultCandidateCount
WithDefaultMaxTokens
WithDefaultTemperature
WithDefaultTopP

llms: llms/googleai/option.go With methods added that was not implemented yet

---

llms/count_tokens.go
llms/generatecontent.go

This adds helpers to make the Parts types a bit easier to work with.

llms: Add usability methods to parts types

---

go.mod
go.sum
internal/mongodb/client.go
llms/chat_messages.go
memory/mongo_chat_history.go
memory/mongo_chat_history_options.go
memory/mongo_chat_history_test.go

memory: Add mongodb memory implementation

---

embeddings/jina/jina.go
embeddings/jina/jina_test.go
embeddings/jina/options.go
examples/bedrock-claude3-vision-example/becrock_claude3_vision_example.go
examples/nvidia-chat-completion/nvidia_chat_completion_example.go
llms/googleai/shared_test/shared_test.go

embeddings: Add Jina

---

llms/bedrock/internal/bedrockclient/provider_anthropic.go

feat: bedrock anthropic stream support

---

agents/openai_functions_agent.go
schema/schema.go

I noticed that after the recent addition of ToolCalls support，it is no longer effective to use the tool with the openai agent. This is because after obtaining the openai results for the first time, the tool was called, but the next request to call openai could not be correctly formed, resulting in empty response. I improved each request and solved the problem
When running the TestExecutorWithOpenAIFunctionAgent in the executor_test.go directory of the agent, both tools will return an empty response, and the result can now be returned correctly

agent: Update openai agent tool calling (#765)

---

docs/docs/modules/model_io/models/llms/Integrations/llamafile.mdx
examples/llamafile-completion-example/go.mod
examples/llamafile-completion-example/go.sum
examples/llamafile-completion-example/llamafile_completion_example.go

-----------------------------------------------
Added examples in the documentation, for better guidance, it is worth remembering that the server for both llamafile and llama.cpp use the same structure so it can be used for both

docs: re-add llamafile example

---

llms/ollama/options.go

docs: fix 'WithKeepAlive' docs

---

llms/openai/internal/openaiclient/chat.go

fix: better handling of errors in openai-like streaming messages

---

examples/openai-completion-example/openai_completion_example.go
examples/openai-function-call-example/openai_function_call_example.go
llms/openai/openaillm.go

Supersedes https://github.com/tmc/langchaingo/pull/829

Improve tool choice population and parsing

---

memory/mongo/mongo_chat_history.go
memory/mongo/mongo_chat_history_options.go
memory/mongo/mongo_chat_history_test.go

memory: move mongo chat history into the separate module

---

go.mod
go.sum
llms/generatecontent.go
llms/marshaling.go
llms/marshaling_test.go
vectorstores/redisvector/index_schema.go

This tidies up the recent marshaling changes.

llms: Tidy up marshaling

---

examples/anthropic-tool-call-example/anthropic-tool-call-example.go
examples/anthropic-tool-call-example/go.mod
examples/anthropic-tool-call-example/go.sum
examples/openai-function-call-example/openai_function_call_example.go
llms/anthropic/anthropicllm.go
llms/anthropic/internal/anthropicclient/anthropicclient.go
llms/anthropic/internal/anthropicclient/messages.go

Implement #716
* add function calling support for anthropic llm
* added `anthropic-tool-use-example`

anthropic: Add tool/function calling support

---

vectorstores/milvus/milvus.go
vectorstores/milvus/milvus_test.go
vectorstores/milvus/options.go

fix(milvus_vectorstore): store metadata with JSON data type & support search with filter

---

llms/cloudflare/cloudflarellm.go
llms/llamafile/llamafilellm.go
llms/maritaca/maritacallm.go
llms/ollama/ollamallm.go

- [n/a] Describes the source of new concepts.
- [n/a] References existing implementations as appropriate.
- [n/a] Contains test coverage for new functions.
- [n/a] Passes all [`golangci-lint`](https://golangci-lint.run/) checks.
This PR fixes two typos in the `ErrIncompleteEmbeddings` message. The first is the word `no` instead of `not` being incorrectly used. The second removes an extraneous `m` in the word `embedded`.  I could not find any other PRs for this. I haven't changed any functionality, only the content of the declared error.

[llms] Fix ErrIncompleteEmbeddings Message Typos

---

llms/maritaca/internal/maritacaclient/maritacaclient.go

marita: update Authorization

---

llms/generatecontent.go
llms/marshaling.go
llms/marshaling_test.go

feat(openai): add the field `detail` in ImageURLContent struct

---

llms/googleai/googleai.go
llms/googleai/vertex/vertex.go

Fix small typo and clean up unused err.

googleai: Remove unused err, fix typo

---

examples/ollama-functions-example/ollama_functions_example.go
llms/ollama/internal/ollamaclient/types.go
llms/ollama/ollamallm.go

ollama: Fix JSON format bug issue when not streaming

---

llms/googleai/shared_test/shared_test.go
llms/googleai/vertex/vertex.go

fix: vertex do not return usage info

llms/googleai: fix vertex do not return usage info

---

llms/googleai/googleai.go
llms/googleai/shared_test/shared_test.go
llms/googleai/vertex/vertex.go

llms/googleai: fix convert tool error

---

go.mod
go.sum
llms/googleai/googleai.go
llms/googleai/shared_test/shared_test.go

Updates generative-ai-go, fix usage in genai backend, fix MaxToken test

llms/googleai: Fix usage population tests, max token test, update dpep

---

docs/docs/modules/model_io/models/llms/Integrations/watsonx.mdx
examples/watsonx-llm-example/go.mod
examples/watsonx-llm-example/go.sum
examples/watsonx-llm-example/watsonx_example.go
go.mod
go.sum
llms/watsonx/watsonxllm.go

The watsonx Go package just got transfered to the official IBM org here: https://github.com/ibm/watsonx-go.
There is also a few API changes along with this.

llms/watsonx: update module

---

examples/watsonx-llm-example/go.mod
examples/watsonx-llm-example/go.sum

examples: point watsonx example at current main

---

llms/anthropic/anthropicllm.go
llms/anthropic/internal/anthropicclient/messages.go
llms/marshaling.go

This improves handling of anthropic streaming messages.

anthropic: Improve streaming message handling in anthropic client

---

llms/anthropic/internal/anthropicclient/anthropicclient.go
llms/anthropic/internal/anthropicclient/completions.go
llms/anthropic/internal/anthropicclient/messages.go
llms/bedrock/internal/bedrockclient/bedrockclient.go
llms/bedrock/internal/bedrockclient/provider_ai21.go
llms/bedrock/internal/bedrockclient/provider_amazon.go
llms/bedrock/internal/bedrockclient/provider_anthropic.go
llms/bedrock/internal/bedrockclient/provider_cohere.go
llms/bedrock/internal/bedrockclient/provider_meta.go
llms/googleai/option.go
llms/openai/internal/openaiclient/completions.go

This increases general default token count to 2048.

llms: Increase default tokens

---

examples/README.md

examples: Improve top level readme

---

examples/anthropic-completion-example/anthropic_completion_example.go
examples/anthropic-tool-call-example/anthropic-tool-call-example.go
llms/anthropic/anthropicllm.go
llms/anthropic/internal/anthropicclient/messages.go

Improves anthropic tool calling example.

anthropic: Spruce up tool calling example

---

examples/googleai-streaming-example/README.md
examples/ollama-stream-example/README.md

Updates examples to the latest release.

examples: Update to v0.1.12

---

llms/anthropic/anthropicllm.go
llms/anthropic/anthropicllm_option.go
llms/anthropic/internal/anthropicclient/anthropicclient.go

anthropic: Add support for beta header

---

llms/anthropic/anthropicllm.go
llms/anthropic/internal/anthropicclient/messages.go

This touches up the error event handling.

anthropic: Add improved handling of other error event types

---

llms/openai/internal/openaiclient/chat.go

This reflects changes in this struct.

openai: add completion_tokens_details to usage response

---

llms/openai/openaillm.go

Adds reasoning tokens to GenerationInfo

openai: add reasoning tokens to usage response

---

llms/openai/internal/openaiclient/chat.go

openai: add reasoning tokens to streaming response

---

.github/workflows/ci.yaml
.golangci.yaml

upgrade golangci to latest version.

ci: upgrade golangci lint version

---

agents/mrkl.go
agents/mrkl_prompt.go

Input to MRKL agent:
```
What's the sum of LeBron James's sons' ages?
```
The MRKL agent's final prompt after iterations:
```
Today is August 01, 2024.
Answer the following questions as best you can. You have access to the following tools:
- calculator: Useful for getting the result of a math expression. 
The input to this tool should be a valid mathematical expression that could be executed by a starlark evaluator.
- GoogleSearch: 
"A wrapper around Google Search. "
"Useful for when you need to answer questions about current events. "
"Always one of the first options when you need to find information on internet"
"Input should be a search query."
Use the following format:
Question: the input question you must answer
Thought: you should always think about what to do
Action: the action to …
```

agents: optimize the mrkl prompt

---

llms/mistral/mistralmodel.go

fix(mistral): supports the default llms.WithTools implementation

---

examples/openai-o1-example/README.md

examples: improve o1 readme

---

examples/openai-jsonformat-example/README.md
examples/openai-jsonformat-example/go.mod
examples/openai-jsonformat-example/openai-jsonformat.go

add OpenAI json structured example

add OpenAI json structured example

---

README.md

docs: Update Discord invite link in README

---

.github/workflows/publish-docs.yaml

V2 of upload artifact was deprecated. This updates to v4 to fix docs publishing.

fix docs publishing

---

.github/workflows/publish-docs.yaml

fix docs publishing, use v3 of upload artifact

---

llms/googleai/googleai.go

Fixes: https://github.com/tmc/langchaingo/issues/1245

googleai: fix issue where gemini would ignore all but the first tool

---

.github/workflows/publish-docs.yaml
docs/docs/concepts/architecture.md
docs/docs/getting-started/guide-mistral.mdx
docs/docs/getting-started/guide-ollama.mdx
docs/docs/getting-started/guide-openai.mdx
docs/docs/modules/agents/executor/getting-started.mdx
docs/docs/modules/agents/index.mdx
docs/docs/modules/data_connection/retrievers/index.mdx
docs/docs/modules/model_io/models/index.mdx
docs/docs/modules/model_io/models/llms/Integrations/fake.mdx
docs/docs/modules/model_io/models/llms/Integrations/groq.mdx
docs/docs/modules/model_io/models/llms/Integrations/huggingface.mdx
docs/docs/modules/model_io/models/llms/index.mdx
docs/docs/modules/model_io/prompts/prompt_templates/index.mdx
docs/go.mod
docs/go.sum
docs/package.json
docs/search-indexer.go
docs/src/theme/SearchBar/SearchBar.css
docs/src/theme/SearchBar/index.js

Follows on from #1311, adds a go indexer for docs search.

docs: follow-on and fix search indexing

---

FIXES_SUMMARY.md
agents/mrkl.go
agents/ollama_agent_guide.md
agents/openai_functions_agent.go
test_all_fixes.sh

Improve agent robustness by enhancing parsing flexibility and handling multiple tool calls properly.
- Added case-insensitive matching for "Final Answer" variations
- Improved Action/Action Input parsing with flexible regex patterns
- Better handling of different model output formats
- Added trimming for cleaner output extraction
- Fixed handling of multiple tool calls in a single response
- Improved scratch pad construction for parallel tool calls
- Better error handling for non-JSON tool arguments
- Proper grouping of tool calls and responses
These changes make the agents more robust when working with different LLM providers that may have slight variations in their output formatting, and properly support the multiple tool calls feature introduced in newer OpenAI models.
All existing …

agents: improve robustness of MRKL and OpenAI Functions agents

---

docs/docs/modules/agents/tools/index.mdx

the link to the documentation of Tools was updated

Tools Doc : URL was not working. 
