examples/QA-example/main.go, vectorStores/pinecone/pinecone.go
Move the namespace field in the pinecone index from a struct field to function argument. This will give users the option to have one pinecone index for multiple namespaces, reducing the api calls done when creating a new pinecone client.
=> Move namespace in pinecone index from a struct field to function argument

examples/local-llm-example/go.mod, examples/local-llm-example/go.sum, examples/local-llm-example/local_llm_example.go, llms/local/internal/localclient/completions.go, llms/local/internal/localclient/localclient.go, llms/local/localllm.go
This implements support for local LLMs.
Tested with various local completion/chat engines.
```
╰─ 〉LOCAL_LLM_BIN="/path/to/alpaca/chat" LOCAL_LLM_ARGS="-m /path/to/alpaca/ggml-alpaca-7b-q4.bin -p" go run .
A square has four equal sides, so it has 4 sides in total.
```
You can test with any local binary if you don't have a local LLM set up on your machine.
For example, `LOCAL_LLM_BIN="/usr/bin/say" LOCAL_LLM_ARGS="-v 'Good News'" go run main.go` works on macOS.
=> Add support for local LLMs

exp/memory/memory.go, exp/textSplitters/textSpliters.go, exp/vectorStores/pinecone/internal/pineconeClient/createIndex.go, exp/vectorStores/pinecone/internal/pineconeClient/query.go, exp/vectorStores/pinecone/internal/pineconeClient/upsert.go
Improvements of #18 
- Removed unnecessary code
- Use `http.StatusXxx` instead of hardcoded numbers when checking http status
- Replaced incorrect use of `fmt.Printf(..)` with `log.Printf(...)` with idiomatic prefixes `[WARN]`
- Replaced incorrect use and deprecated `ioutil.ReadAll(...)` with `*bytes.Buffer` and `io.Copy(...)` for better performance
=> chore: improve code qualities and use idiomatic way to implementation

.github /PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
I found out PR titles were often hard to understand and navigate, and PR descriptions were often missing or just not following a stable or readable pattern when developers organizing it. So I added the `.github /PULL_REQUEST_TEMPLATE.md` to help everyone get more clear about how to write and what to write obviously when they submitting the PR.
- Added `.github /PULL_REQUEST_TEMPLATE.md` for Pull Request template
- Tweaked the `CONTRIBUTING.md` file to state out the PR title requirements, removed unnecessary terms in `CONTRIBUTING.md`
=> docs: added Pull Request template and improved CONTRIBUTING.md

.github/workflows/lint-build-test.yaml, exp/chains/llmChain_test.go, exp/vectorStores/pinecone/internal/pineconeClient/upsert.go
**summary:** add's CI linting, building, and testing. Corrects existing lint failures.
closes https://github.com/tmc/langchaingo/issues/6
=> ci: Add linting, building, and testing to ci

.golangci.yaml
Adjustments:
- Adjusted the line limit of `funlen` linter to `90`.
- Added `run.skip-dirs` in configuration with `exp` dir ignored
=> lint: adjust the line limit of funlen linter to 90

exp/agent/mrkl/mrkl.go, exp/prompts/chat_template.go
Fixed:
- Missing return issue in `exp/prompts/chat_template.go`
- Unexpected token in `exp/agent/mrkl/mrkl.go`
=> exp/prompts: fix missing return and unexpected token

.gitignore, go.mod, go.sum, prompts/doc.go, prompts/example_selector.go, prompts/prompt.go, prompts/prompt_template.go, prompts/prompt_template_test.go, prompts/prompt_test.go, prompts/templates.go, prompts/templates_test.go, schema/output_parsers.go
Implement partially #31 
Implemented:
- `PromptTemplater` interface, is a equivalent
- `PromptTemplate` along with the member methods, one of the implementation of `PromptTemplater`
- constructor of `PromptTemplate` from options, examples
- `StringPromptValue` implementation, one of the implementation to `schema.PromptValue`
- `ExampleSelector` interface
References:
- https://github.com/hwchase17/langchainjs/blob/main/langchain/src/prompts/index.ts
- https://github.com/hwchase17/langchainjs/blob/main/langchain/src/prompts/prompt.ts
- https://github.com/hwchase17/langchainjs/blob/main/langchain/src/prompts/base.ts
- https://github.com/hwchase17/langchainjs/blob/main/langchain/src/prompts/template.ts
- https://github.com/hwchase17/langchain/blob/master/langchain/prompts/prompt.py
- …
=> prompts: introduced PromptTemplate along with the relevant types

CONTRIBUTING.md
Updated a typo on the link to [bug_tracker], there's another typo on for the byzanz tool to screen record on linux, but wasn't entirely sure where that was supposed to point. Found [this](https://gitlab.gnome.org/Archive/byzanz), if this is the desired link I can add it, otherwise I could remove it.
=> typo: link directed to 404 page, updated typo

vectorstores/pinecone/restapi.go
- fix panic in pinecone doRequest() function if resp is nil
```console
[INF] storing generated embeddings in pinecone
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x40 pc=0x1014e1f28]
goroutine 1 [running]:
github.com/tmc/langchaingo/vectorstores/pinecone.doRequest({0x101706578, 0x14000192018}, {0x101673480?, 0x140004d7260?}, {0x140000421e0, 0x57}, {0x140001cd440, 0x24}, {0x1014e488f, 0x4})
/Users/tarun/go/pkg/mod/github.com/tmc/langchaingo@v0.0.0-20230514182324-27d8b7bf4dda/vectorstores/pinecone/restapi.go:187 +0x2d8
github.com/tmc/langchaingo/vectorstores/pinecone.Store.restUpsert({{0x101705510, 0x140001a1470}, 0x0, {0x0, 0x0}, {0x1014e8331, 0x7}, {0x1014eeca2, 0xf}, {0x1014f5f94, ...}, ...}, ...) …
```
=> pinecone: fix panic in doRequest

vectorstores/pinecone/options.go, vectorstores/pinecone/pinecone_test.go, vectorstores/vectorstores.go
This adds options to the vectorstore ToRetriever function that are used when doing similarity search. The result is that you can specify a name space to search in when creating a retriever from the pinecone vector store. A test using the pinecone vectorstore in a retrievalQA chain is also added.
=> vectorstores: add options to ToRetriever 

.gitignore, llms/openai/internal/openaiclient/completions.go, llms/openai/internal/openaiclient/openaiclient.go
This MR adds a variadic `Option` to the OpenAI client, allowing for future customizations. It also adds the `WithHTTPClient` option that allows setting custom HTTP clients.
Closes #90 
contributor.
=> Feat(openaiclient): add Option for custom HTTP client

llms/openai/openaillm.go, llms/openai/openaillm_option.go
This removes unneeded code in the `llms` package: the sync.once is not needed, the default options can just be initialized in when New() is called.
contributor.
=> Refactor(llms): simplify option handling

vectorstores/pinecone/options.go, vectorstores/pinecone/pinecone.go
This MR fixes some docstrings in the pinecone package.
contributor.
=> Fix(pinecone): correct docstrings

examples/openai-chat-example/go.mod, examples/openai-chat-example/go.sum
=> fix: sync go module to latest in openai-chat-example

prompts/chat_prompt.go, prompts/chat_prompt_template.go, prompts/chat_prompt_template_test.go, prompts/message_promt_templage.go, prompts/prompt_template.go, prompts/prompt_template_test.go, prompts/prompts.go, prompts/templates.go
This adds chat prompt templates and prompt templates for each of the message types. All message type prompt templates implement the new message formatter interface. GetInputVariables is added to the format prompter because the llm chain needs to know what input values the prompt needs. The checks for "stop" is removed because stop values are now given in the call options. A prompt value for chat messages is added.
Fixes #134.
=> prompts: add chat prompt template

examples/huggingface-llm-example/huggingface_example.go, examples/local-llm-example/local_llm_example.go, llms/local/internal/localclient/completions.go, llms/local/internal/localclient/localclient.go, llms/local/localllm.go, llms/local/localllm_option.go
---
Hello! 
This PR implements the enhancements proposed in ticket #116 for the Local LLM package.
The update includes the following changes:
- The `localllm` package now includes `options`, which implement specific functions such as `WithBin`, `WithArgs`, and `WithGlobalAsArgs`.
- These new functionalities are embedded within the logic of the `localllm` package, hence, setting the environment variables `LOCAL_LLM_BIN` and `LOCAL_LLM_ARGS` is no longer mandatory - everything can now be performed programmatically.
- The most significant part of the update comes with the activation of the `WithGlobalAsArgs` option. This option compels the package to utilize specific global options of `llms.CallOption` during its operation. If an option is not set or is equal to zero, then it will not be …
=> feat: LocalLLM improvments, llms.CallOptions as local-llm call arguments

vectorstores/options.go, vectorstores/pinecone/pinecone.go, vectorstores/pinecone/restapi.go, vectorstores/weaviate/weaviate.go, vectorstores/weaviate/weaviate_test.go
Hello,
This is the implementation of the Weaviate version of Filter as in pull request #129. 
Your review and feedback are greatly appreciated.
In order to make it possible to implement across various vector stores, the type restriction has been removed, similar to the [langchainjs](https://github.com/hwchase17/langchainjs/blob/main/langchain/src/vectorstores/base.ts) implementation.
=> vectorstores:  Weaviate Add filter logic　

agents/conversational.go, agents/initialize.go, agents/mrkl.go, chains/api.go, chains/api_test.go, chains/chains.go, chains/errors.go, chains/llm.go, chains/llm_math.go, chains/prompt_selector.go, chains/question_answering.go, chains/refine_documents.go, chains/retrival_qa.go, chains/stuff_documents.go, chains/summarization.go
This changes the chains and agents packages to use the language model interface instead of the LLM interface so that chat models can be used. The predict function is also added to execute chains that returns a single string. The function exists in the python and typescript version.
https://github.com/hwchase17/langchain/blob/afc292e58d768d96245272ebe7d985f72b03da73/langchain/chains/llm.py
=> chains: use langauge model instead of LLM and add predict 

chains/chains.go, chains/conversation.go, chains/conversation_test.go
This adds a function to create a llm chain for conversations like:
https://github.com/hwchase17/langchainjs/blob/main/langchain/src/chains/conversation.ts
This also modifies the run function to remove keys gotten from the memory when checking if the chain only expects one input.
=> chains: add conversation chain and fix run

vectorstores/weaviate/weaviate.go
Hello,
I have added error handling when fetching data in Weaviate.
For example, including a property name in the search that is not pre-defined in Weaviate will result in a panic.
I have modified this so that it does not cause a panic, but instead returns an error.
=> vectorstores: add error handling of weaviate.Get() function

tools/duckduckgo/ddg.go, tools/duckduckgo/internal/client.go
- Adding a `user-agent` fixes `403` response status which seems to happen randomly.
- Adding a subdomain `html` to the search url to avoid a redirect (`302` response status).
- Also: accepting the `maxResults` and `userAgent` via the `New` func.
You can test the redirects with curl:
```
curl -sf -o /dev/null -D - 'https://duckduckgo.com/html/?q=olivia%20wilde' | grep 'HTTP\|ocation'
HTTP/2 302
location: https://html.duckduckgo.com/html/?q=olivia%20wilde
```
vs
```
curl -sf -o /dev/null -D - 'https://html.duckduckgo.com/html/?q=olivia%20wilde' | grep 'HTTP\|ocation'
HTTP/2 200
```
=> tools/duckduckgo: fix for response status 403 and 302

llms/huggingface/internal/huggingfaceclient/huggingfaceclient.go, llms/huggingface/internal/huggingfaceclient/huggingfaceclient_test.go, llms/huggingface/internal/huggingfaceclient/inference.go
When using the Hugging Face client, parameters are not being correctly included in the `inferencePayload`, causing the Inference API to ignore them. The [docs](https://huggingface.co/docs/api-inference/detailed_parameters#text-generation-task) for performing a text generation task specify that the parameters should be specified in the body of the request like so:
```json
{
"inputs": "Can you please let us know more details about your ",
"parameters": {
"top_k": 10
}
}
```
but we're currently doing this:
```json
{
"inputs": "Can you please let us know more details about your ",
"top_k": 10
}
```
I've been able to test locally that this proposed change works.
=> huggingface: build inferencePayload appropriately

chains/chains_test.go, chains/conversation.go, chains/llm.go, chains/llm_test.go, chains/map_reduce_test.go
This improves some of the tests in the chain package and adds the possibility to use chat prompt templates in the llm chain. This also exports the llm and prompt in the llm chain.
=> chains: improve testing

chains/chains.go, chains/map_reduce.go, chains/map_rerank_documents.go, chains/map_rerank_documents_test.go, chains/question_answering.go, chains/question_answering_test.go, docs/parity_matrix.md, outputparser/doc.go, outputparser/regex_parser.go
#68.
Relevant Documents:
- [LangChain Map Rerank](https://docs.langchain.com/docs/components/chains/index_related_chains#map-rerank).
- [Python Implementation](https://github.com/hwchase17/langchain/pull/516).
Would appreciate sanity check here, not sure I fully grok this chain. I believe this behaves similarly to its python counterpart, with some functionality provided by @FluffyKebab's `MapReduce` addition.
Changes:
- Moves `_intermediateStepsOutputKey` var to central file (out of `chains/map_reduce.go`).
- Fixes the output of the `RegexParser` so it can be used by LLM chains, updates/adds some documentation.
- Adds MapRerankDocuments functionality.
=> feature: map rerank chain

docs/parity_matrix.md, outputparser/combining.go, outputparser/combining_test.go, outputparser/doc.go, outputparser/regex_parser.go, outputparser/structured.go
References:
- [langchain (python) combining output parser](https://github.com/hwchase17/langchain/blob/master/langchain/output_parsers/combining.py).
Changes:
- Adds the output parser combining.
- Small update to the regex parser instructions.
=> feat(outputparser): Add Combining Output Parser

chains/chains_test.go, chains/errors.go, chains/llm_test.go, chains/map_reduce_test.go, chains/map_rerank_documents_test.go, chains/sequential.go, chains/sequential_test.go, internal/util/util.go
* Implementation of `SimpleSequentialChain` and `SequentialChain`. Addresses #114.
* Will add examples once this is merged - looks like I can't add an example with this PR.
* [Python source](https://github.com/hwchase17/langchain/blob/master/langchain/chains/sequential.py)
=> chains: simplesequentialchain and sequentialchain implementation

docs/parity_matrix.md, outputparser/doc.go, outputparser/regex_dict.go, outputparser/regex_dict_test.go
References:
- [langchain (python) regex dict output parser](https://github.com/hwchase17/langchain/blob/master/langchain/output_parsers/regex_dict.py).
Changes:
- Adds functionality `outputparser` `RegexDict`.
=> feat(outputparser): Add Regex Dict Parser

docs/parity_matrix.md, outputparser/boolean_parser.go, outputparser/boolean_parser_test.go, outputparser/doc.go
References:
- [langchain (python) boolean output parser](https://github.com/hwchase17/langchain/blob/master/langchain/output_parsers/boolean.py).
Changes:
- Adds functionality `outputparser` `BooleanParser`.
=> outputparser: Add BooleanParser

chains/llm_azure_test.go, llms/openai/internal/openaiclient/chat.go, llms/openai/internal/openaiclient/completions.go, llms/openai/internal/openaiclient/embeddings.go, llms/openai/internal/openaiclient/openaiclient.go, llms/openai/openaillm.go, llms/openai/openaillm_option.go
This PR adds the support for azure openai support.
Some major changes
https://github.com/openai/openai-python/blob/main/openai/__init__.py
Some concerns: may cause some users' compatibility issues. 
We can discuss about it. Whether we prefer the alignment or the compatibility. 
Also I can change the code adding "v1" it in the buildURL method if the compatibility wins.
Same as the feature in the python implementation. 
Doc: https://python.langchain.com/docs/modules/model_io/models/llms/integrations/azure_openai_example
Url Base Construction: https://github.com/openai/openai-python/blob/main/openai/api_resources/abstract/api_resource.py
The embedding still can not work in Azure API, the embeddings/embedding.go batchText
https://learn.microsoft.com/en-us/answers/questions/1189661/openai-sente …
=> llm: add azure api support

examples/cohere-llm-example/cohere_completion_example.go, examples/cohere-llm-example/go.mod, examples/cohere-llm-example/go.sum, go.mod, go.sum, llms/cohere/coherellm.go, llms/cohere/coherellm_option.go, llms/cohere/internal/cohereclient/cohereclient.go, llms/doc.go
This pull request introduces support for [cohere](https://cohere.com)'s LLM text generation
It doesn't incorporate yet all the options from cohere's API, currently only the prompt is available.
I tried to keep the same structure as the other LLM implementations.
I also added the dependency [github.com/cohere-ai/tokenizer](https://chat.openai.com/github.com/cohere-ai/tokenizer). This was necessary to implement the GetNumTokens function without necessitating a request to cohere's API.
Mirroring the OpenAI implementation, the token must be specified via the COHERE_API_TOKEN environment variable, while the model is set with the COHERE_MODEL variable.
[Python Implementation](https://github.com/hwchase17/langchain/blob/master/langchain/llms/cohere.py)
=> llms: add cohere support

chains/conversational_retrieval_qa.go, chains/conversational_retrieval_qa_test.go, chains/question_answering.go
- implementing https://python.langchain.com/docs/modules/chains/popular/chat_vector_db
- closing issue https://github.com/tmc/langchaingo/issues/205
=> feat: Feature request: Conversational Retrieval QA

memory/buffer.go, memory/buffer_options.go, memory/buffer_test.go, memory/chat.go, memory/chat_options.go, schema/chat_message_history.go
- adding the ability to port in any memory integration for the buffer
- by this logic, we can pass in any store that we would like to have to keep track of the chat history
=> feat: Memory Integrations (chat history)

agents/conversational_test.go, chains/conversation_test.go, chains/conversational_retrieval_qa.go, chains/conversational_retrieval_qa_test.go, chains/errors.go, chains/sequential_test.go, memory/buffer.go, memory/buffer_options.go, memory/buffer_test.go, memory/chat.go, memory/chat_test.go, memory/doc.go, memory/simple.go, memory/token_buffer.go, memory/token_buffer_test.go, schema/chat_message_history.go, schema/memory.go
- this PR fixes the Conversational retrieval interface to accept `schema.Memory` instead of the `memory.Buffer`, by that we can in future pass in any memory that we need (for example Buffer, TokenBuffer or any other that we add).
- I've also renamed `Buffer` to be `ConversationBuffer` and `TokenBuffer` to be `ConversationTokenBuffer` so that we are closer to the langchain python implementation, so that it is easier on the eyes when we are comparing what is what.
- updated `ChatMessageHistory` schema to support errors, we need that when we port in psql, mongo or any other driven history, so that we don't swallow the errors when/if we have them
=> memory: Feature conversational retrieval interface fix and rename

examples/sql-database-chain-example/sql_database_chain.go, examples/zapier-llm-example/main.go, llms/anthropic/anthropicllm.go, llms/anthropic/anthropicllm_option.go, llms/anthropic/internal/anthropicclient/anthropicclient.go, llms/anthropic/internal/anthropicclient/completions.go
Adds Anthropic LLM implementation.
=> llms: Add anthropic LLM implementation

chains/api.go
Current api chain supports only `HTTP GET`, this PR upgrades the chain with the ability to perform `PUT`, `POST`, `DELETE`. 
The `reqChain` is updated to build and return a json string representing the request based on the provided API docs. The temp for request chain is set to 0.0 to ensure consistent json formatting.  The `HTTPRequester` interface is changed to support full CRUD capabilities. 
Once the request is performed the answer chain will summarise and inform about the API response, will handle success and various errors.
=> Chains/api chain CRUD support upgrade

llms/local/internal/localclient/completions.go, llms/local/localllm.go
I attempted to use Llama with LangChainGo utilizing the "local" LLM, but encountered some issues when I tried to send arguments (specifically the model path) to the binary.
I faced an error when I tried using local.WithArgs("-m <path_to_the_model> -p"). It seemed as if the list of arguments was being sent to exec.CommandContext as a single argument.
Once I got it up and running, I noticed that extra quotes were added to the prompt.
To me, it seems like it was designed to be parsed by Bash, but it doesn't appear to be so.
I'm not entirely sure if this is actually a bug, or perhaps I used it incorrectly. If it's supposed to work like this, feel free to close this PR.
=> locallms: Split arguments with spaces in & remove quote around prompt

vectorstores/options.go
- this option allows us to use different embedders, if we have single vectorstore (like posgresql) which can handle (storing/using) multiple embeddings.
```
....
// dummy list of embedders
embedders := map[string]embedder.Embedder{
"openai": openaiEmbedder,
"huggingface": huggingfaceEmbedder,
"vertexai": vertexaiEmbedder,
"someother": someotherEmbedder,
}
emd := embedders["openai"] // dummy example pulling the embedders from the list of supported embedders
result, err := chains.Run(
context.TODO(),
chains.NewRetrievalQAFromLLM(
llm,
vectorstores.ToRetriever(store, 5, vectorstores.WithNameSpace(id), vectorstore.WithEmbedder(emb)),
),
"What colors is each piece of furniture next to the desk?",
)
....
```
from this point on, our `store` when the `AddDocuments` or `SimilaritySearch` methods …
=> vectorstore/options: Extending Vectorstore options to accept optional embedder

embeddings/huggingface/huggingface.go, embeddings/huggingface/huggingface_test.go, embeddings/huggingface/options.go, llms/huggingface/huggingfacellm.go, llms/huggingface/internal/huggingfaceclient/embeddings.go, llms/huggingface/internal/huggingfaceclient/huggingfaceclient.go, llms/huggingface/internal/huggingfaceclient/inference.go
- creating hugging face embedder, which we need when we want to use embeddings with the huggingface model
=> embeddings/huggingface: Creating embedder for the Huggingface hub

tools/sqldatabase/mysql/mysql.go, tools/sqldatabase/mysql/mysql_test.go, tools/sqldatabase/postgresql/postgresql.go, tools/sqldatabase/postgresql/postgresql_test.go, tools/sqldatabase/sqlite3/sqlite3.go, tools/sqldatabase/sqlite3/sqlite3_test.go
Currently when using sql chain on tables with nullable columns, it will return converting null to string error is not supported. To mitigate this issue, I'm suggesting to use sql.NullString to handle null values.
Fixes https://github.com/tmc/langchaingo/issues/235
=> bugfix: sql null column error

prompts/few_shot.go, prompts/few_shot_test.go
Added FewShotPrompt. Fixes #196.
[Python source](https://github.com/hwchase17/langchain/blob/master/langchain/prompts/few_shot.py)
=> prompts: FewShotPrompt implementation

chains/llm_azure_test.go, embeddings/openai/openai_test.go, llms/openai/internal/openaiclient/chat.go, llms/openai/internal/openaiclient/completions.go, llms/openai/internal/openaiclient/embeddings.go, llms/openai/internal/openaiclient/openaiclient.go, llms/openai/llm.go, llms/openai/openaillm_option.go
- if we want to use azure openai implementation, we need to provide the needed embedder model (aka deployment in the Azure portal), this is the required parameter in the Azure documentation
- each deployment in azure is used for diff purpose
- fixing the issue and adding the tests
=> embeddings/azure-openai: Fixing issues with azure openai implementation

embeddings/vertexai/vertexai_palm_test.go, embeddings/vertexai/vertexaichat/options.go, embeddings/vertexai/vertexaichat/vertexai_chat.go, embeddings/vertexai/vertexaichat/vertexai_chat_test.go, llms/vertexai/vertexai_palm_llm.go, llms/vertexai/vertexai_palm_llm_chat.go, textsplitter/split_documents.go
- splitting up vertexai llm per files, to be encapsulated/maintainable and easier on the eyes
- creating the actual embedding that we will use for the Chat llm (until now we couldn't use it)
- tests added
- https://github.com/tmc/langchaingo/pull/225 - there was the same issue for the open ai
=> embeddings & llm: Creating the actual embeddings for the VertexAI chat, splitting llms for VertexAI

llms/openai/internal/openaiclient/chat.go
when try with the exsample code: [https://github.com/tmc/langchaingo/blob/main/examples/openai-chat-example/openai_chat_example.go](url). 
I found there is an index out of range panic, by further check when the llm.Call receives only human message, the streamResponse.Choices will be empty.
fix by add boundary check
=> code fix: index out of range when streamResponse.Choices is empty

llms/openai/openaillm_chat.go
Conversion of messages from `schema.Message*` to openai client messages seems have been moved to a dedicated function but the old code was still there.
Question for maintainers: 
This case
```
case schema.ChatMessageTypeAI:
msg.Role = RoleAssistant
if aiChatMsg, ok := m.(schema.AIChatMessage); ok && aiChatMsg.FunctionCall != nil {
msg.FunctionCall = &openaiclient.FunctionCall{
Name:      aiChatMsg.FunctionCall.Name,
Arguments: aiChatMsg.FunctionCall.Arguments,
}
}
```
isn't handled by `messagesToClientMessages` here: https://github.com/urjitbhatia/langchaingo/blob/main/llms/openai/openaillm_chat.go#L156
is that on purpose or an accidental omission?
=> cleanup: remove unused msg conversion - openaillm_chat

llms/openai/internal/openaiclient/openaiclient.go
When using the openai API with the `AZURE_AD` type, I found that there was an error when making the API call. After debugging, I discovered that the authentication field in the header was incorrectly set to `api-key` instead of `Authorization`.
```go
if IsAzure(c.apiType) {
req.Header.Set("api-key", c.token)
} else {
req.Header.Set("Authorization", "Bearer "+c.token)
}
```
change to :
```go
if c.apiType == APITypeOpenAI || c.apiType == APITypeAzureAD {
req.Header.Set("Authorization", "Bearer "+c.token)
} else {
req.Header.Set("api-key", c.token)
}
```
Please refer to the implementation in the Python OpenAI library:
https://github.com/openai/openai-python/blob/9d559b064cda09d56c1ebf756be4a1f73d5a275a/openai/util.py#L21C1-L25C2
=> Fixed OpenAI APITypeAzureAD header authentication field error

llms/vertexai/vertexai_palm_llm_option.go
This is a small PR that allows the user to pass options to the VertexAI client initalisation.
=> Added possiblity to add options to VertexAI client

prompts/templates.go
Fixes #287 
Currently, `prompts` package uses `sprig.FuncMap()` as the template's function map, which is an instance of the `html/template.FuncMap` type. However, the `interpolateGoTemplate` function uses `text/template` for template generation and requires a `text/template.FuncMap`. Although there is no significant distinction between the two in Go 1.19 and later versions, for versions prior to 1.19, the `interpolateGoTemplate` function will result in an error. This PR uses `sprig.TxtFuncMap()` as the template's function map.
=> prompts: use sprig.TxtFuncMap() as the template's function map

llms/vertexai/internal/vertexaiclient/palm_client.go, llms/vertexai/vertexai_palm_llm.go
At the moment langchaingo's vertexai client doesn't include `stop_sequences`, this leads to problems with agents when the prediction doesn't stop at `Observation:` which then will include hallucinated tool output.
=> Added stop_sequences support to vertexai client

llms/openai/internal/openaiclient/chat.go, llms/openai/internal/openaiclient/chat_test.go
This Pull Request addresses an existing issue in the `parseStreamingChatResponse` function. Specifically, the `FinishReason` field in the `ChatResponse` struct was not being populated based on the incoming streamed HTTP response. 
- Added logic to capture the `FinishReason` from the `StreamedChatResponsePayload` and assign it to the `ChatResponse`.
- Implemented a unit test to validate this specific behavior, ensuring the `FinishReason` field is correctly populated.
=> bugfix: add missing FinishReason when streaming

llms/openai/openaillm.go
openai.New(openai.WithModel("model_name")) not work, it will use defaultEmbeddingModel as "text-embedding-ada-002"
=> bugfix: openai fix model option

.github/workflows/ci.yaml
=> ci: Pin golangci-lint to 1.54

llms/ernie/erniellm.go, llms/ernie/erniellm_option.go
This PR adds a new enumeration value to support the ernie 4.0 model in llms.
The only difference in invoking the ernie 4.0 model compared to previous versions is the API path. This path is defined as a series of enumerations, and I've introduced an additional enum value to accommodate the ernie 4.0 model.
=> llms: add enum for ernie 4.0 API path

embeddings/openai/openai.go, embeddings/openai/openai_test.go
=> embedding/openai: fix method-dependent embedding discrepancy

embeddings/internal/embedderclient/embedderclient.go, embeddings/vertexai/vertexai_palm.go, embeddings/vertexai/vertexaichat/vertexai_chat.go
Starting with the vertex embedder, but this is applicable to others too.
The common code fixes the combined vector issue, similarly to #357, for #356
This replaces a completely duplicated method in two places with a common function; the same function can be used for the embedders of other LLMs as well, if this approach is deemed good.
=> embeddings: refactor EmbedderClient interface to reduce code duplication

examples/ernie-completion-example/ernie_completion_example.go, examples/ernie-completion-example/go.mod, examples/ernie-completion-example/go.sum
Right now it's in the main module, the only example of this kind.
Align it with the other examples.
This is a two step change, and this is step 1; step 2 will be updating
this example's go.mod to rely on a newer version of langchaingo that
no longer provides this package.
This change has to comment out the example's contents for the lint
to pass -- the issue is that both the main module and this new module
provide the package.
=> examples/ernie-completion-examples: make this example a separate module

examples/ernie-completion-example/ernie_completion_example.go, examples/ernie-completion-example/go.mod, examples/ernie-completion-example/go.sum
This sets the go.mod to point to a newer version of the parent module, so now there's no conflict and everything builds and lints.
This is part 2, followup on #365
=> examples/ernie-completion-examples: make this example a separate module part 2

documentloaders/notion.go, documentloaders/notion_test.go
This PR adds the NotionDirectoryLoader feature to Go, similar to its [Python counterpart](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/document_loaders/notion.py). The loader manages fetching and arranging local Notion Markdown files from a specified directory.
=> documentloaders: add notion directory loader

go.mod, go.sum, vectorstores/chroma/doc.go, vectorstores/pgvector/doc.go, vectorstores/pgvector/options.go, vectorstores/pgvector/pgvector.go, vectorstores/pgvector/pgvector_test.go, vectorstores/pinecone/doc.go, vectorstores/weaviate/doc.go
=> vectorstores: add pgvector

vectorstores/pgvector/options.go
Added support for Postgres Schemas. 
The table is named `"mySchema"."myTable"` instead `"mySchema.myTable"`.
=> pgvector: support postgres schema

vectorstores/pgvector/pgvector.go
See issue #440. `DropTables()` returns an error:
```
ERROR: cannot drop table "Collections" because other objects depend on it (SQLSTATE 2BP01)
```
Switched the order to drop the `s.embeddingTableName` Table first, and then the `s.collectionTableName` Table.
=> pgvector: Fix DropTable Function

llms/openai/llm.go, llms/openai/openaillm_option.go
there are many code in langchain use env `OPENAI_API_BASE`:
https://github.com/search?q=repo%3Alangchain-ai%2Flangchain%20OPENAI_API_BASE&type=code
such as: https://github.com/langchain-ai/langchain/blob/583696732cbaa3d1cf3a3a9375539a7e8785850c/libs/community/langchain_community/embeddings/azure_openai.py#L62
just add code to read backup env name `OPENAI_API_BASE` to campatible with langchain
=> feat: read OPENAI_API_BASE env to compatible with langchain

embeddings/embedding.go, embeddings/embedding_test.go, internal/util/util.go, internal/util/util_test.go
Fixes #322 
This is how it's done in langchain js package https://github.com/langchain-ai/langchainjs/blob/4e9e23137de8d2bc61dfbcf05e8e35a8f1e89ef5/langchain/src/embeddings/openai.ts#L154
Current implementation batches the []texts by taking each text and **dividing** them into _batchSize_ chars instead of **grouping** the texts into _batchSize_ elements
If texts are ["abcd", "efgh", "ijkl", "mnop"] and batchSize is 2, current implementation breaks it into [ ["ab", "cd"], ["ef", "gh"], ... ] instead of [ ["abcd", "efgh" ], ["ijkl", "mnop"] ]
=> embeddings: Fix BatchTexts function

agents/conversational.go, agents/mrkl.go, chains/llm.go
=> support callback handler to llm chain

memory/window_buffer.go, memory/window_buffer_test.go
Port the [ConversationBufferWindowMemory](https://python.langchain.com/docs/modules/memory/types/buffer_window) class from [langchain python](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/memory/buffer_window.py) in langchaingo
=> memory: add ConversationWindowBuffer

chains/conversational_retrieval_qa_test.go, chains/question_answering_test.go
Planning for #465, we need tests to pass as much as possible. Some QA-related tests fail right now (#415) - let's skip them so we have a clean passing test slate to use for refactoring. When the tests are fixed they can be unskipped.
=> Skip tests that are currently failing (#415)

prompts/templates.go, prompts/templates_test.go
A recent unrelated CI failure https://github.com/tmc/langchaingo/actions/runs/7359418374/job/20034158813?pr=464#step:5:599 shows that we have an unstable comparison and "jinja2" isn't appropriately used everywhere.
=> templates: Fix up gonja/jinja2 handling

textsplitter/markdown_splitter.go
The markdown splitter was not correctly handling singular markdown tokens
like Hr or Fence. These tokens do not have a corresponding close type,
which was causing issues in the indexOfCloseTag function.
To fix this, a check has been added to return the start index if the
closeType is nil, indicating a singular token. This prevents the function
from incorrectly trying to find a close tag for these tokens and running
past the end of the document.
=> textsplitter: handle singular markdown tokens in markdown_splitter

schema/schema.go
It exists in the llms package already
=> Remove duplicated and unused LLMResult type from schema

llms/generatecontent.go, llms/llms.go, llms/openai/internal/openaiclient/chat.go, llms/openai/multicontent_test.go, llms/openai/openaillm_chat.go
First sketch for #465, including an OpenAI implementation.
Also adding real tests that require API key to be set.
I'm marking this API as experimental so we can work on it without disrupting other code, initially.
=> GenerateContent - initial experimental API with OpenAI implementation

chains/chains_test.go, llms/anthropic/anthropicllm.go, llms/cohere/coherellm.go, llms/cohere/internal/cohereclient/cohereclient.go, llms/ernie/ernie_chat.go, llms/ernie/erniellm.go, llms/huggingface/huggingfacellm.go, llms/llms.go, llms/local/localllm.go, llms/ollama/ollamallm.go, llms/ollama/ollamallm_chat.go, llms/openai/openaillm.go, llms/openai/openaillm_chat.go, llms/vertexai/vertexai_palm_llm.go, llms/vertexai/vertexai_palm_llm_chat.go, memory/token_buffer.go
It's not used and not implemented correctly for almost any model.
See #482 for details
If this is deemed useful, it will be more correct to expose a model name from the LLM (or cliena?) and then invoke a standalone function familiar with non-openai models.
=> Clear out GetNumTokens

llms/openai/internal/openaiclient/chat.go, llms/openai/internal/openaiclient/chat_test.go
- [x ] Read the [Contributing documentation](https://github.com/tmc/langchaingo/blob/main/CONTRIBUTING.md).
- [x ] Read the [Code of conduct documentation](https://github.com/tmc/langchaingo/blob/main/CODE_OF_CONDUCT.md).
- [x ] Name your Pull Request title clearly, concisely, and prefixed with the name of the primarily affected package you changed according to [Good commit messages](https://go.dev/doc/contribute#commit_messages) (such as `memory: add interfaces for X, Y` or `util: add whizzbang helpers`).
- [x ] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [ x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `Fixes #123`).
- [x ] Describes the source of new …
=> fix unmarshalling of chatmessage

llms/ollama/chatoptions.go, llms/ollama/ollama_test.go, llms/ollama/ollamallm_chat.go
Following #405, the custom prompting is no longer needed since we now use the `/chat` endpoint of Ollama for chats.
This helps clean out a bunch of code!
Adding test for ollama that can be run locally by setting the `OLLAMA_TEST_MODEL` env var (otherwise skip).
=> Add Ollama test and remove custom prompt for chat

llms/googleai/googleai_llm.go, llms/googleai/googleai_llm_test.go, llms/googleai/googleai_option.go
Set up provider-specific options instead of exposing google client options to users
Add implementation of embedding + test
re #410
=> googleai: set up options and embeddings

llms/generatecontent.go, llms/googleai/googleai_llm.go, llms/googleai/googleai_llm_test.go, llms/llms.go, llms/openai/multicontent_test.go, llms/openai/openaillm_chat.go
Generalizes the interface to enable chat interactions as well as single-message interactions
Re #410 and #465
=> Extend Model / GenerateContent interface to support multi-content chats

llms/googleai/googleai_llm_test.go, llms/openai/multicontent_test.go
Add multi-turn tests for new GenerateContent capabilities
For both openai and googleai providers
=> Add multi-turn tests for new GenerateContent capabilities

llms/googleai/googleai_llm.go
Recently the streaming endpoint returns a nil-Content candidate; account for it in the streaming logic.
=> googleai: fix streaming termination

.golangci.yaml, llms/googleai/download.go, llms/googleai/googleai_llm.go, llms/googleai/googleai_option.go
=> googleai: move downloadImageData to separate file

CONTRIBUTING.md, vectorstores/weaviate/options.go, vectorstores/weaviate/weaviate.go, vectorstores/weaviate/weaviate_test.go
Via `queryAttrs` you can specify fields to be returned with a similarity search. In Weaviate you can retrieve [additional properties](https://weaviate.io/developers/weaviate/api/graphql/additional-properties#available-additional-properties) via the `_additional` field. With the current setup it is not possible to add additional fields (like the id) to the the `_additional` field due to the [manual mapping](https://github.com/tmc/langchaingo/blob/main/vectorstores/weaviate/weaviate.go#L276-L281) in 'createFields' function.
This adds a new `WithAdditionalFields` optional to give the user control over which additional fields to return.
=> vectorstores: Weaviate make additional fields configurable

vectorstores/options.go, vectorstores/weaviate/weaviate.go, vectorstores/weaviate/weaviate_test.go
A new function, MetadataSearch, has been added to the Weaviate store. This
function allows for searching Weaviate based on metadata rather than on
similarity. The function takes a context, the number of documents to return,
and a set of options as parameters. It uses these to create a GraphQL query
which is then sent to the Weaviate server. The response is parsed and returned
as a slice of schema.Document.
In addition to the function itself, a test, TestMetadataSearch, has been added
to verify the functionality of the new MetadataSearch function. The test
creates a new Weaviate store, adds some documents to it, and then uses the
MetadataSearch function to retrieve documents based on their metadata. The
results are then checked to ensure they match the expected output.
The addition of this …
=> weaviate: add option to deduplicate documents while adding

embeddings/embedding.go, vectorstores/weaviate/weaviate.go, vectorstores/weaviate/weaviate_test.go
An adapter for the EmbedderClient interface has been added. This allows
the use of ordinary functions as Embedder Clients. This change provides
flexibility in implementing the EmbedderClient interface, as it allows
any function with the appropriate signature to be used as an
EmbedderClient.
The changes allow the embedder to be overridden in the vectorstores options.
This is done by changing the embedder calls in `AddDocuments` and `SimilaritySearch`
functions to use the embedder from the options instead of the store.
The default embedder is still the one from the store, but it can be overwritten
by passing a `vectorstores.WithEmbedder` option.
A new test case 'TestWeaviateWithOptionEmbedder' is added to ensure that the
embedder provided as an option to either `AddDocuments` or …
=> weaviate: honor vectorstores.WithEmbedder

textsplitter/markdown_splitter.go, textsplitter/markdown_splitter_test.go, textsplitter/options.go
Enhance markdown text splitting functionality by adding handlers for
markdown code blocks, fences, and horizontal rules. This change allows
the markdown splitter to properly process and format these elements,
improving the accuracy of the text splitting process.  However, long
code blocks and fenced blocks will be split as text and won't be
properly wrapped, which is a known limitation that aligns with the
current behavior of the python langchain.
The markdown splitter function 'splitInline' has been significantly
enhanced to handle a variety of inline elements as per the CommonMark
specification. Previously, it simply returned the content of the inline
element. Now, it checks for the presence of children in the inline
element and processes them accordingly.
This change was necessary to …
=> textsplitter: render code blocks and reference links

agents/executor_test.go, agents/openai_functions_agent.go, llms/llms.go
sync the newest main branch today find that openai_functions_agent.go still use old llms.Chat Generate function and can't compile
=> bug fix: openai_functions_agent not compatible with the new llms.Model interface

.golangci.yaml, llms/anthropic/anthropicllm.go, llms/cohere/coherellm.go, llms/ernie/erniellm.go, llms/googleai/googleai_llm.go, llms/huggingface/huggingfacellm.go, llms/llms.go, llms/local/localllm.go, llms/ollama/ollamallm.go, llms/openai/openaillm.go, llms/vertexai/vertexai_palm_llm.go
So we can use it in examples as well
=> llms: rename convenience function to GenerateFromSinglePrompt

docs/docs/modules/data_connection/vector_stores/pgvector.mdx
A simple documentation page for pgvector integration, in response to [this request](https://github.com/tmc/langchaingo/pull/534#pullrequestreview-1834369765).
There is no "Integrations" page in the docs, so I put it under /data_connectons/vector_stores.
=> docs: add pgvector page

llms/huggingface/huggingfacellm.go, llms/huggingface/huggingfacellm_option.go, llms/huggingface/internal/huggingfaceclient/huggingfaceclient.go, llms/huggingface/internal/huggingfaceclient/huggingfaceclient_test.go
When using huggingface with bigger models we need to be able to set a custom inference endpoint. This PR allows to set this option.
=> huggingface: allows to set custom inference endpoint

embeddings/huggingface/huggingface_test.go
Fixes the typo of 'openaiKey' in huggingface_test.go.
=> embeddings: fix variable typo in huggingface_test

vectorstores/pgvector/options.go, vectorstores/pgvector/pgvector.go
-----
Added an option to PGVector to set the collection metadata
There was no way to set the collection metadata even though the struct had a field for it.
Therefor, I added an option so you can specify the metadata. If the collection already exists, the metadata gets updated.
Fixes #556
=> vectorstores: Added an option to PGVector to set the collection metadata

vectorstores/pgvector/options.go, vectorstores/pgvector/pgvector.go
----
Added an option to specify the vector dimensions for the embeddings
This is needed when you eventually want to add [an HNSW index](https://github.com/pgvector/pgvector#hnsw) to the embeddings to speed up the querying.
=> vectorstores: Added an option to specify the vector dimensions for the embeddings

agents/markl_test.go, agents/mrkl.go
This small code change is to allow the one-shot zero agent to pass multi-line input to a tool. I did not change the conversational one as the regex there is different from this one to start with and is missing unit tests (so I cannot confirm breaking changes).
Change is setting the `s` flag to true on the regex.
=> agents: [OneShotZeroAgent] Change regex to allow multi-line inputs

textsplitter/recursive_character.go, textsplitter/recursive_character_test.go
fix #607  #231 
Add the newSeparators array to avoid entering an infinite loop call.
Inspired by https://github.com/langchain-ai/langchain/blob/00a09e1b7117f3bde14a44748510fcccc95f9de5/libs/langchain/langchain/text_splitter.py.
=> fix: stackoverflow caused by textspliter

go.mod, go.sum, vectorstores/chroma/chroma.go
This is a small change to support the addition of context params on chroma-go api. Those changes were merged on Jan 9. [PR #20](https://github.com/amikos-tech/chroma-go/pull/20).
=>  chroma: update chroma-go functions to pass context

chains/llm_test.go
Resurrect test from #625, but add explicit settings until #626 is resolved
=> chains: add test with GoogleAI

chains/api_test.go, chains/llm_test.go, chains/options.go
Updates #626
Fixes #603
Fixes #604
Fixes #594
This is a backwards compatible fix until we fix #626 for real.
Note that the workaround can now be removed in the GoogleAI chains test.
=> chains: fix issue with overriding defaults in chainCallOption

llms/ernie/internal/ernieclient/chat.go, llms/openai/internal/openaiclient/chat.go
> A colon as the first character of a line is in essence a comment, and is ignored.
ref: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#event_stream_format
I haven't seen openai officially use colons in SSE, but I have seen openai-like services use colons to prevent connections from being disconnected, for example: `: ping - 2024-02-23 06:52:12.876102` by LLaMA-Factory
=> llms: fix SSE stream should ignore comment

chains/options.go
=> chains: fix add ignore StreamingFunc

go.mod, go.sum
I'm making a major overhaul of the chroma-go package, so I need to pin the version until the upgrade is done, at which point I'll create a PR for any breaking changes.
=> chore: Pinning chroma-go ahead of major new release

callbacks/agent_final_stream.go, callbacks/agent_final_stream_test.go
I did a little change in this PR to handled 2 problems when using AgentFinalStreamHandler:
I followed  this example to study using agent
https://github.com/tmc/langchaingo/blob/main/examples/mrkl-agent-example/mrkl_agent.go
and use a handler to get streaming result  like this:
```go
callbackHandler := callbacks.NewFinalStreamHandler()
// callbackHandler.PrintOutput = true
executor, err := agents.Initialize(
llm,
agentTools,
agents.ZeroShotReactDescription,
agents.WithMaxIterations(5),
agents.WithCallbacksHandler(callbackHandler),
)
```
reason: cut out slice handler.LastTokens before doing detect keyword will cause Detection can’t success
for example:  
before the handler.LastTokens string value is 
```
"result Final Answer: As of February 18,"
```
after the reassign the slice value, it's …
=> Fix agent stream callback

examples/ollama-functions-example/go.mod, examples/ollama-functions-example/go.sum, examples/ollama-functions-example/ollama_functions_example.go, llms/ollama/ollama_test.go, llms/ollama/ollamallm.go, llms/ollama/options.go
A new functionality was introduced to allow the setting of a specified
data format (currently Ollama only supports JSON). This is done via the
`WithFormat` option. The change provides more flexibility and control
over the format of data processed by the client.
Moreover, the test `TestWithFormat` has been added to assert the proper
functioning of this new feature.
Using the JSON format allows you to simulate `Functions` using prompt
injection, as it forces Ollama to respond in valid JSON.
Add an example showing how the Ollama `JSON` format in combination with
prompt injection can be used to simulate Functions.
Output:
```bash
$ go run .
2024/03/06 11:03:24 Call: getCurrentWeather
2024/03/06 11:03:25 Call: finalResponse
2024/03/06 11:03:25 Final response: The forecast for Beijing is sunny …
```
=> feat: add JSON format option to ollama

agents/mrkl_prompt.go
change prompt the same as python version:
Current mrkl-prompt in langchaingo would get some very weird answer when I Don't need to use agent-tools in a agent conversation. 
Seems like It's forced llm to use some tool to get the Final Answer 
And this is langchain python mrkl-prompt:
```python
PREFIX = """Answer the following questions as best you can. You have access to the following tools:"""
FORMAT_INSTRUCTIONS = """Use the following format:
"""
```
This have no problem
---
=> change mrkl-prompt to python version

docs/docs/modules/agents/index.mdx, docs/docs/modules/agents/tools/index.mdx, docs/docs/modules/chains/index.mdx, docs/docs/modules/chains/llm_chain.mdx, docs/docs/modules/data_connection/document_loaders/index.mdx, docs/docs/modules/data_connection/index.mdx, docs/docs/modules/data_connection/retrievers/index.mdx, docs/docs/modules/data_connection/text_splitters/index.mdx, docs/docs/modules/data_connection/vector_stores/index.mdx, docs/docs/modules/memory/index.mdx, docs/docs/modules/model_io/models/chat/index.mdx, docs/docs/modules/model_io/models/embeddings/index.mdx, docs/docs/modules/model_io/models/index.mdx, docs/docs/modules/model_io/models/llms/index.mdx, docs/docs/modules/model_io/output_parsers/index.mdx, docs/docs/modules/model_io/prompts/index.mdx, docs/docs/modules/model_io/prompts/prompt_templates/index.mdx, docs/docusaurus.config.js
It seems like a bunch of links were broken and docs.langchain.com now redirects to the python docs.
=> docs: fixup a bunch of links

docs/docs/modules/data_connection/retrievers/index.mdx
A example about retriever, how use and why need use
=> docs: Add example about retriever

docs/docs/modules/data_connection/text_splitters/examples/index.mdx
=> docs: Add documentation for splitters

llms/anthropic/anthropicllm.go, llms/anthropic/anthropicllm_option.go, llms/anthropic/internal/anthropicclient/anthropicclient.go, llms/anthropic/internal/anthropicclient/completions.go
This PR implements the WithBaseURL and WithHTTPClient options for the anthropic llms and wires them up. This implementation was derived from the `llms/openai` implementation. This is needed to enable using a tool such as [Helicone](https://www.helicone.ai) with the Anthropic models (I suspect more people may start using them thanks to Claude 3).
=> llms/anthropic: Implement WithBaseURL and WithHTTPClient for Anthropic LLM

examples/ollama-functions-example/ollama_functions_example.go
This example hangs if the JSON data is either marked as human or AI, it only works for me when marked as system. This PR makes it so the example no longer hangs.
=> This example hangs if the JSON data is either marked as human or AI, it only works for me when marked as system

.golangci.yaml, documentloaders/assemblyai.go, documentloaders/assemblyai_test.go, go.mod, go.sum
This PR adds the AssemblyAI document loader from [LangChain](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/document_loaders/assemblyai.py) and [LangChain JS](https://github.com/langchain-ai/langchainjs/blob/main/langchain/src/document_loaders/web/assemblyai.ts).
Unfortunately, due to the number of supported formats (in `formatTranscript()`), I had to increase the `cyclop` max complexity from 10 to 12. I first tried to break up the switch case, but then the `exhaustive` check failed. 
I could also split the loader into a loader for each format. Let me know if you'd prefer it that way.
=> documentloaders: add AssemblyAI document loader

llms/openai/llm.go, llms/openai/openaillm_option.go
Using the `openai.New()` for models with `APITypeAzure`  without the `model` parameter results in a missing path parameter. Example from request dump: 
```
POST /openai/deployments//chat/completions?api-version=2024-02-15-preview HTTP/1.1
```
Create a new Azure OpenAI LLM using this code:
```go
llm, err := openai.New(
openai.WithAPIType(openai.APITypeAzure),
openai.WithToken(token),
openai.WithBaseURL(baseURL),
openai.WithEmbeddingModel("text-embedding-ada-002"),
openai.WithAPIVersion("2024-02-15-preview"),
)
```
This should fail with a 404 status - url is set to one like above.
Add the `WithModel` parameter, like this:
```go
llm, err := openai.New(
openai.WithAPIType(openai.APITypeAzure),
openai.WithToken(token),
openai.WithBaseURL(baseURL),
openai.WithModel("openai-gpt-35-turbo"), …
```
=> llms/openai: Azure: add check for `model` parameter

examples/openai-completion-example-with-http-debugging/go.mod, examples/openai-completion-example-with-http-debugging/go.sum, examples/openai-completion-example-with-http-debugging/openai_completion_example.go
Follow-on from #702 to use it.
=> examples: Use new debugging helper in example

vectorstores/chroma/chroma_test.go, vectorstores/milvus/milvus_test.go, vectorstores/opensearch/opensearch_test.go
Fixes #705 by running env checks sooner.
=> tests: Perform env-var checking skips sooner as to speed up tests

examples/anthropic-completion-example/anthropic_completion_example.go, llms/anthropic/anthropicllm.go, llms/anthropic/anthropicllm_option.go, llms/anthropic/internal/anthropicclient/anthropicclient.go, llms/anthropic/internal/anthropicclient/completions.go, llms/anthropic/internal/anthropicclient/messages.go
This adds full support for the new messages API including streaming. 
It backwards compatible with client option flag for using message api. 
It also updates the default model to 1.3 as 1.0 isn't supported by either completions or messages API.
Closes #695
=> llms/anthropic: adds full support for messages api

llms/bedrock/internal/bedrockclient/provider_anthropic.go
This PR concerns the execution of a prompt to recognize images using llms/bedrock's Claude3 model. In this PR, I would like to address some errors that occur when executing the following code.
```go
package main
import (
"context"
_ "embed"
"log"
"github.com/tmc/langchaingo/llms"
"github.com/tmc/langchaingo/llms/bedrock"
"github.com/tmc/langchaingo/schema"
)
//go:embed image.png
var image []byte
func main() {
llm, err := bedrock.New(
bedrock.WithModel(bedrock.ModelAnthropicClaudeV3Haiku),
)
if err != nil {
log.Fatal(err)
}
ctx := context.Background()
resp, err := llm.GenerateContent(
ctx,
[]llms.MessageContent{
{
Role: schema.ChatMessageTypeHuman,
Parts: []llms.ContentPart{
llms.BinaryPart("image/png", image),
llms.TextPart("Please text what is written on this image."),
},
},
},
)
if err …
```
=> llms/bedrock: Fixed error when using Claude3 model and giving MessageContent with images

examples/ernie-function-call-example/ernie_function_call_example.go, examples/openai-function-call-example/openai_function_call_example.go, examples/openai-function-call-streaming-example/openai_function_call_example.go, llms/cloudflare/cloudflarellm.go, llms/cloudflare/internal/cloudflareclient/api.go, llms/cloudflare/internal/cloudflareclient/api_test.go, llms/cloudflare/internal/cloudflareclient/client.go, llms/cloudflare/internal/cloudflareclient/model.go, llms/cloudflare/internal/cloudflareclient/role.go, llms/cloudflare/options.go, tools/scraper/scraper.go
This PR implements Cloudflare Workers AI LLM as documented [here](https://developers.cloudflare.com/api/operations/workers-ai-post-run-model). Functionality is at parity with [Langhain's](https://github.com/langchain-ai/langchain) Cloudflare Workers AI [implementation](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/llms/cloudflare_workersai.py).
=> llms/cloudflare: Implement Cloudflare Workers AI LLM

examples/bedrock-claude3-vision-example/go.mod, examples/caching-llm-example/go.mod, examples/openai-chat-example/openai_chat_example.go, llms/openai/internal/openaiclient/chat.go
=> openai: Render single text content parts directly

go.mod
https://go.dev/ref/mod#go-mod-file-go
----
**go directive**
A go directive indicates that a module was written assuming the semantics of a given version of Go. The version must be a valid [Go version](https://go.dev/doc/toolchain#version), such as 1.9, 1.14, or 1.21rc1.
The go directive sets the minimum version of Go required to use this module. Before Go 1.21, the directive was advisory only; now it is a mandatory requirement: Go toolchains refuse to use modules declaring newer Go versions.
----
Per https://github.com/golang/go/issues/62278#issuecomment-1693538776, `go 1.22` is insufficient and may return errors for "go1.22 toolchain not available"
=> all: set explicit 1.22 version in go.mod

examples/openai-function-call-example/go.mod, examples/openai-function-call-example/go.sum, examples/openai-function-call-example/openai_function_call_example.go, llms/anthropic/anthropicllm.go, llms/bedrock/internal/bedrockclient/provider_anthropic.go, llms/cloudflare/cloudflarellm.go, llms/generatecontent.go, llms/googleai/googleai.go, llms/llamafile/llamafilellm.go, llms/mistral/mistralmodel.go, llms/ollama/ollamallm.go, llms/openai/internal/openaiclient/chat.go, llms/openai/internal/openaiclient/chat_test.go, llms/openai/internal/openaiclient/completions.go, llms/openai/internal/openaiclient/openaiclient.go, llms/openai/llm.go, llms/openai/multicontent_test.go, llms/openai/openaillm.go, llms/options.go, schema/chat_messages.go, schema/chat_messages_test.go
This adds tool implementation which generalizes function calling.
This focuses on the openai inference backend. Related filed issues: #716 
Fixes #712, Refs #507
=> llms: Implement tool calling, including parallel tool call request support

examples/openai-embeddings-example/openai-embeddings-example.go, llms/openai/internal/openaiclient/embeddings.go
__________________________________________________________
References a Issue #729
=> openai:  WithEmbeddingModel option is incorrectly designating the desired model to use for embedding

llms/mistral/mistralmodel.go, llms/openai/internal/openaiclient/chat.go, llms/openai/internal/openaiclient/completions.go, llms/openai/openaillm.go
_______________________________________
Ref Issue #723
=> llms: Add Seed option to all supporting backends 

tools/serpapi/options.go, tools/serpapi/serpapi.go
It is often desirable to be able to control the names of environment variables and not having them predefined by the package. This PR allows to pass Serpapi API key as an configuration option, while maintaining backwards compatibility with existing applications.
=> tools: serpapi api key option

docs/docs/getting-started/guide-openai.mdx
This MR resolves an issue with the rendering of a code block from the [docs/getting-started/guide-openai](https://tmc.github.io/langchaingo/docs/getting-started/guide-openai) docs page. 
- Remove unnecessary whitespace that causes rendering issues.
You can observe the rendering issue within the following section (https://tmc.github.io/langchaingo/docs/getting-started/guide-openai#steps):
Notice that the second step gets rendered as if it were in a code block. Removing the extra spacing fixes this block.
=> docs: resolve rendering issue with code block in getting started docs

examples/pinecone-vectorstore-example/pinecone_vectorstore_example.go
Description:
This PR addresses an issue in the example code for the Pinecone vector store in the langchaingo package. The current code does not specify an embedding model when instantiating the Language Model (LLM), resulting in the API returning an unexpected status code: 400 - "you must provide a model parameter." This can lead to unexpected behavior or errors. The proposed change adds a line to specify the embedding model, ensuring the code runs correctly and aligns with best practices.
Changes:
Added a line to specify the embedding model when instantiating LLM in the Pinecone example code.
Please review and merge at your earliest convenience.
Thank you!
=> Fix: Specify embedding model when instantiating LLM in Pinecone example code

go.mod, llms/openai/internal/openaiclient/chat.go, llms/openai/openaillm.go, llms/options.go
There are OpenAI servers (like LiteLLM) that takes in additional `metadata` in their requests to log additional information. In LiteLLM's case, the metadata field is used to store information like custom tags and trace ids which will be propagated to Langfuse. 
In [Langchain Python](https://api.python.langchain.com/en/latest/chat_models/langchain_community.chat_models.openai.ChatOpenAI.html#langchain_community.chat_models.openai.ChatOpenAI.model_kwargs), there are model_kwargs argument to achieve this, however it's difficult to add kwargs to structs for deserialization in Go. Therefore we'll need to hardcode a metadata field here.
=> Add metadata fields in OpenAI calls

examples/groq-completion-example/go.mod, examples/groq-completion-example/go.sum, examples/groq-completion-example/groq_completion_example.go
Add usage example for [groq](https://console.groq.com/docs/quickstart)
groq offers the same API like OpenAPI
https://github.com/tmc/langchaingo/issues/797
=> Add groq completion example

vectorstores/opensearch/options.go
This commit corrects an errors handling issue in the applyClientOptions function within the opensearch options module.
Previously, when the opensearch client was missing, the function erroneously returned ErrMissingEmbedded instead of ErrMissingOpensearchClient.
This update ensures that the current error is returned.
- [] Contains test coverage for new functions.
=> bugfix: incorrect error return in applyClientOptions function

examples/chains-conversation-memory-sqlite/chains_conversation_memory_sqlite.go, memory/sqlite3/sqlite3_history.go, memory/sqlite3/sqlite3_history_options.go, memory/sqlite3/sqlite3_history_test.go
Add sqlite3 support for chat memory history.
=> Chat Memory History: add sqlite3 backend

go.mod, textsplitter/options.go, textsplitter/recursive_character.go, textsplitter/recursive_character_test.go
Fix issue #720 
Reference Implementation In Python:  [RecursiveCharacterTextSplitter](https://api.python.langchain.com/en/latest/_modules/langchain_text_splitters/character.html#RecursiveCharacterTextSplitter)
=> feat: add WithKeepSeparator option for RecursiveCharacter

llms/openai/internal/openaiclient/chat.go
I noticed that after the recent addition of ToolCalls support that streaming with functions/toolCalls is no longer working. I created this PR to add tool calls support to the streaming functionality.
you can see this in action if you call this example: https://github.com/tmc/langchaingo/blob/main/examples/openai-function-call-streaming-example/openai_function_call_example.go
This example with current code will not print this final message. With the change in this PR you will see the correct result
Expected output:
```
Function call: &{getCurrentWeather {
"location": "Boston, MA",
"rationale": "User asked for the current weather in Boston"
}}
```
=> openai: add toolcalls support when streaming

vectorstores/pgvector/options.go, vectorstores/pgvector/pgvector.go
Restores WithConnectionURL option.
=> pgvector restore WithConnectionURL option

prompts/chat_prompt_template.go
There may be situation where promptValue is nil which will cause panic while accessing promptValue.Messages()
```
func (p ChatPromptTemplate) FormatMessages(values map[string]any) ([]llms.ChatMessage, error) {
promptValue, err := p.FormatPrompt(values)
if promptValue == nil {
return nil, err
}
return promptValue.Messages(), err
}
```
=> fix: handle nil pointer exception in chat_prompt_template

llms/generatecontent.go, llms/marshaling.go, llms/marshaling_test.go
This adds standard yaml marshaling of `llm.MessageContent` types with special casing for single-text-part messages.
=> llms: Add improved yaml and json marshaling

vectorstores/chroma/README.md
Perhaps this worked before, but now if you omit the protocol in the URL, you'll get an error like this:
```
2024/05/21 10:15:43 new: Get "localhost:8000/api/v1/heartbeat": unsupported protocol scheme "localhost"
```
- [n/a] Describes the source of new concepts.
- [n/a] References existing implementations as appropriate.
- [n/a] Contains test coverage for new functions.
- [n/a] Passes all [`golangci-lint`](https://golangci-lint.run/) checks.
=> readme: add scheme to vectorstores/chroma URL

llms/googleai/googleai.go
🔧 Added support for 'array' type in the convertToolSchemaType function to map it to genai.TypeArray. This enhances the functionality by enabling correct type handling for array types.
- Improved the type conversion logic by including the 'array' case.
- Ensures that 'array' types are not set to TypeUnspecified but correctly set to TypeArray.
- With this change you can now include Arrays in your Google JSON Schema tool definitions without error, like you could already with other LLMs
=> feat(googleai): add support for array type in convertToolSchemaType

llms/count_tokens.go
/kind cleanup
Fix typos map key value of the modelToContextSize.
=> Fix typos map key value of the modelToContextSize

llms/openai/internal/openaiclient/chat.go
OPENAI stream return usage info
=> openai: enable optional return of usage data while streaming

examples/groq-completion-example/go.mod, examples/groq-completion-example/go.sum, examples/groq-completion-example/groq_completion_example.go
Related To: #890
- Added `godotenv` to load environment variables from `.env` file.
- Corrected the initialization of the OpenAI client to include `openai.WithToken(apiKey)` for proper Groq API key usage.
- Updated the example to reflect the correct usage and included necessary error handling for missing API keys.
This change addresses the confusion regarding the API key parameter and ensures proper integration with the Groq API.
I still think there should be a separate module to load models for Groq instead of OpenAI, for better readability.
=> examples: Correct API key usage for Groq integration

llms/anthropic/anthropicllm.go
Fixed a bug from previous PR #882 where Anthropic LLM couldn't identify the input arguments of a function call from the message history.
=> bugfix: Anthropic Function Calling 

examples/anthropic-tool-call-example/anthropic-tool-call-example.go, llms/anthropic/anthropicllm.go, llms/anthropic/internal/anthropicclient/messages.go
=> llms/anthropic: Fix Content set incorrectly for anthropic llm requests

docs/docs/modules/data_connection/text_splitters/examples/index.mdx
just fixing this page: https://tmc.github.io/langchaingo/docs/modules/data_connection/text_splitters/examples/ with a little bug in the example code preview.
=> docs: fix text_splitters mdx code example never closed

textsplitter/markdown_splitter.go, textsplitter/markdown_splitter_test.go, textsplitter/options.go, textsplitter/testdata/example_markdown_header_512.md
This PR adds a WithHeadingHierarchy option to the markdown textsplitter to prepend the heading hierarchy to chunks in Markdown documents instead of only current heading.
This improves retrieval of relevant chunks by a higher-level heading.
Input:
```
foobar
bazbom
spam eggs
```
... will yield the last chunk as 
```
spam eggs
```
... so that a semantic search by either h1, h2 or h4 will likely return this chunk.
=> textsplitter: add WithHeadingHierarchy option to markdown splitter to retain heading hierarchy in chunks

examples/googleai-completion-example/googleai-completion-example.go, examples/googleai-tool-call-example/googleai-tool-call-example.go, examples/json-mode-example/json_mode_example.go, llms/googleai/new.go, llms/googleai/option.go
This is the env var name the gemini examples typically use, as far as I can tell.
=> googleai: Settle on GOOGLE_API_KEY for google auth env var name

llms/openai/internal/openaiclient/chat.go, llms/openai/internal/openaiclient/completions.go, llms/openai/openaillm.go
The max_tokens field has been deprecated: https://platform.openai.com/docs/api-reference/chat/create#chat-create-max_tokens
I have not yet changed the high level API as that will require a bit more thought, but this changes the payload representation to not send this deprecated field. This is important for the o1 models which do not support that max_tokens.
=> openai: reflect max_token field deprecation

llms/llms.go
This is not a bug right now (rather a slight optimization), because llms/llms.go (func GenerateFromSinglePrompt) uses unkeyed fields (at llms.TextContent{prompt}), which could potentially lead to a bug in the future.
=> llms: GenerateFromSinglePrompt struct literal uses unkeyed fields

docs/docs/modules/model_io/output_parsers/index.mdx
Added missing Type method, interface `OutputParser` in documentation is now identical to the `/schema/output_parser.go`
=> fix(docs): Type method missing from OutputParser

outputparser/boolean_parser.go, outputparser/boolean_parser_test.go
The BooleanOutputParser requests the LLM to respond with a boolean, and gives examples such as `true` or `false`. However, it only parsed respones that include YES or NO. This commits adds more values for parsing and changes the tests to fit them.
=> outputparser: improve BooleanOutputParser

outputparser/defined.go
The DefinedOutputParser prompted the LLM with a Typescript schema, but expected a json in response: https://github.com/tmc/langchaingo/blob/1975058648b5914fdd9dc53434c5b59f219e2b5c/outputparser/defined.go\#L65-69 Now it also requests a json.
=> outputparser: improve DefinedOutputParser

textsplitter/markdown_splitter.go, textsplitter/markdown_splitter_test.go, textsplitter/options.go
Originally the MarkdownTextSplitter would split tables into chunks
for each row (producing a header + single row) in each chunk. This
change adds an option to join multiple rows into a single chunk.
Fixes: #938
=> textsplitter: add option to join table rows

examples/vertex-completion-example/go.mod, examples/vertex-completion-example/go.sum, llms/googleai/googleai.go, llms/googleai/vertex/vertex.go, llms/options.go
This PR fixes #905. It allows using the already existing _CallOption_ `WithJSONMode()` for _googleai_ and _vertex_ by setting the `ResponseMIMEType` field of the request to `application/json`. Additionally, it introduces a new _CallOption_ `WithResponseMIMEType(string)` that can be used to directly set the `ResponseMIMEType` field on requests for _googlai_ and _vertex_. An error is returned when both _CallOptions_ are set by the user.
=> googleai: add support for JSONMode and ResponseMIMEType

llms/openai/internal/openaiclient/chat.go, llms/openai/internal/openaiclient/openaiclient.go, llms/openai/llm.go, llms/openai/openaillm.go, llms/openai/openaillm_option.go, llms/openai/structured_output_test.go, llms/options.go
https://openai.com/index/introducing-structured-outputs-in-the-api/
=> openai: add support for sending  Structured Output request for chat completions api

vectorstores/redisvector/index_search.go, vectorstores/redisvector/redis_vector_test.go
* Redis vector range queries [expect a radius](https://redis.io/docs/latest/develop/interact/search-and-query/advanced-concepts/vectors/#vector-range-queries) rather than a score threshold.
* The existing code passed the score threshold through directly as the radius param. This means that a higher score threshold will result in in more matches than a lower score threshold which seems wrong. Instead this PR subtracts the score threshold from 1.
* The langchain project appears to have deprecated score threshold in favour of distance threshold. A future improvement would be to add a `WithDistanceThreshold` option for consistency.
* This PR is a breaking change for clients using redisvector and `WithScoreThreshold`. An alternative would be to keep the existing behaviour but add …
=> redisvector: fix score threshold option

vectorstores/milvus/milvus.go, vectorstores/milvus/options.go
When importing a large number of documents at once, flushing during each `AddDocuments` can significantly increase the time taken.
In my scenario, I create a new collection, insert datas, and then replace the original collection, so there is no need to flush every time data is inserted.
Add an option `skipFlushOnWrite` to optimize this scenario. In my test scenario, the total time was reduced from 38 minutes to 5 minutes.
=> milvus: add skipFlushOnWrite option

outputparser/structured.go
Replaces `strings.Split` of two-element splits to use the more modern `strings.Cut` which doesn't allocate a slice. The ergonomics are almost the same so while a small optimization, I feel it's a good idea to use it.
=> outputparser: use strings.Cut in structured parser

examples/mrkl-agent-example/mrkl_agent.go, examples/zapier-llm-example/main.go
Replace deprecated `agents.Initialize` calls by  `agents.NewOneShotAgent` in `mrkl-agent-example` and `zapier-llm-example` examples.
=> examples: replace deprecated agents.Initialize

llms/bedrock/internal/bedrockclient/provider_anthropic.go
As you can see in the aws sdk, when an error is set then stream channel is closed:
- https://github.com/aws/aws-sdk-go-v2/blob/main/service/bedrockruntime/eventstream.go#L84
- https://github.com/aws/aws-sdk-go-v2/blob/main/service/bedrockruntime/eventstream.go#L85
- https://github.com/aws/aws-sdk-go-v2/blob/main/service/bedrockruntime/eventstream.go#L71
The stream channel was read, but once closed, the error was not checked.
You can reproduce a bug triggering a streaming completion response and cancelling the context. The `context.Canceled` error is not returned.
I'm adding it just for anthropic provider because is the only one that supports streaming at present.
=> bedrock: Fix unchecked error when stream channel is closed

examples/pgvector-vectorstore-example/README.md
A minor issue with pgvector example README:
https://docs.docker.com/compose/migrate/
Compose V1 used to be available as `docker-compose`. It reached its end of life last year.
Compose V2 is available as `docker compose` (no dash), and if you don't have an alias, the example will fail.
Related to https://github.com/tmc/langchaingo/issues/956
=> examples: replaced compose v1 with compose v2 in readme for pgvector example

vectorstores/pgvector/pgvector.go, vectorstores/pgvector/pgvector_test.go
=> Fixes #974 - returning score driven by cosine similarity by (1 - distance) instead of distance

.github/workflows/ci.yaml, chains/chains_test.go, llms/ernie/internal/ernieclient/ernieclient.go, llms/ernie/internal/ernieclient/ernieclient_test.go, llms/openai/internal/openaiclient/chat.go, llms/openai/internal/openaiclient/openaiclient.go
Hello.
Thank you for maintaining this great module!
I would like to:
- fix https://github.com/tmc/langchaingo/issues/281#issuecomment-2510861762
- add `-race` flag in go test CI to avoid data race.
- fix data race in test case https://github.com/tmc/langchaingo/actions/runs/12115516980/job/33774019172?pr=1080
=> chore: fix data races

vectorstores/pinecone/pinecone.go, vectorstores/weaviate/weaviate.go
It reverse the logic in Weaviate and Pinecone stores to not return an error if zero docs are retrieved from a SimilaritySearch.
Closes https://github.com/tmc/langchaingo/issues/1065
=> fix(vectorstores:weaviate|pinecone): do not return error when zero documents are retrieved

textsplitter/markdown_splitter.go, textsplitter/markdown_splitter_test.go
Based on the custom lenFuc already supported in `RecursiveCharacter` splitter in [8734b6](https://github.com/tmc/langchaingo/commit/8734b60555715d08b6255b4731dc9bc3317227d2).
=> textsplitter: add an optional lenFunc to MarkdownTextSplitter

vectorstores/mongovector/mongovector_test.go
Containerize mongovector tests using testingcontainer-go.
=> test: containerize mongovector tests

examples/deepseek-completion-example/deepseek-completion-example.go, examples/deepseek-completion-example/go.mod, llms/chat_messages.go, llms/generatecontent.go, llms/openai/internal/openaiclient/chat.go, llms/openai/internal/openaiclient/chat_test.go
I added ReasoningContent field for deepseek-reasoner model based on these official DeepSeek docs: https://api-docs.deepseek.com/api/list-models
=> Add ReasoningContent field for deepseek-reasoner model

.github/workflows/ci.yaml, .golangci.yaml, chains/map_reduce.go, chains/map_rerank_documents.go, documentloaders/csv.go, documentloaders/notion_test.go, examples/deepseek-completion-example/deepseek-completion-example.go, examples/maritaca-example/maritaca-chat-example.go, examples/zep-memory-chain-example/main.go, llms/bedrock/internal/bedrockclient/provider_anthropic.go, llms/huggingface/internal/huggingfaceclient/huggingfaceclient_test.go, llms/maritaca/maritacallm.go, memory/token_buffer.go, memory/window_buffer.go, outputparser/boolean_parser.go, prompts/templates.go, vectorstores/chroma/chroma.go, vectorstores/mongovector/mongovector_test.go, vectorstores/weaviate/options.go
- **chore: use slices and maps packages**
- **chore: skip embedded type**
- **chore: use fmt.Fprint instead**
- **chore: use switch**
- **chore: reorder imports**
- **chore: add white lines**
- **chore: use t.Setenv**
- **chore: excplicitly omit non used param**
- **chore: use t.TempDir**
- **chore: use maps package**
- **chore: migrate golangci-lint config file**
- **chore: bump golangci-lint action to v7**
It migrates golangci-lint to the recently released v2, which changed the config file format.
```shell
golangci-lint migrate -c .golangci.yaml --skip-validation
```
I just removed a few of the linters/formatters it applied because they were not applied before the migration and they complaint with more errors that I was not able to easily resolve:
- `forcetypeassert`
- `recvcheck`
- …
=> ci: migrate linting golangci-lint to v2.0.2

llms/openai/multicontent_test.go
---
When running `multicontent_test.go` under `llms/openai` got error:
`API returned unexpected status code: 404: The model gpt-4-vision-preview has been deprecated, learn more here: https://platform.openai.com/docs/deprecations`
Follow the deprecations guide link above :
Thus, I changed: `gpt-4-vision-preview` -> `gpt-4o` in the `multicontent_test.go`
=> llms/openai: replace deprecated gpt-4-vision-preview with gpt-4o in TestMultiContentImage

tools/duckduckgo/internal/client.go
Presently if the DDG API returns a non-200 status you get a really generic error message that is basically of no help what-so-ever.
This PR basically just shares the HTTP response in the error message
=> duckduckgo: descriptive error message

agents/executor.go, agents/executor_test.go, agents/markl_test.go
fix a bug that cause params error
=> agents: Add more robust response handling to executor.go

llms/ollama/internal/ollamaclient/testdata/TestClient_GenerateChatWithThink.httprr, llms/ollama/testdata/TestWithThink.httprr
- Add httprr test recordings for the think parameter tests
- Tests can now run without requiring a live Ollama server
This is a follow-up to #1349 which was already merged. That PR added:
- Think parameter support for Ollama 0.9.0+
- Test functions for the feature
This PR adds the actual test recordings that were generated with Ollama 0.11.0.
- `TestWithThink.httprr` - High-level test recording showing think:true in request
- `TestClient_GenerateChatWithThink.httprr` - Low-level client test recording
```bash
go test -v ./llms/ollama/...
```
All tests pass ✅
=> ollama: Add httprr test recordings for think parameter

llms/googleai/googleai.go, llms/googleai/vertex/vertex.go
Fix tool conversion to properly support multiple tools in Google AI and Vertex AI by consolidating them into a single Tool object with multiple FunctionDeclarations.
Google's genai SDK requires all function declarations to be within a single Tool object, not multiple Tool objects. When multiple tools were provided, the API would fail or only recognize the first tool.
Modified `convertTools()` in both `llms/googleai/googleai.go` and `llms/googleai/vertex/vertex.go` to:
- Collect all FunctionDeclarations into a single array
- Return a single Tool containing all function declarations
- Handle empty tool lists properly by returning nil
- https://github.com/GoogleCloudPlatform/generative-ai/issues/636
- https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/function-calling#chat-sampl …
=> llms/googleai: fix multi-tool support for Google AI and Vertex AI

go.mod, go.sum, vectorstores/dolt/doc.go, vectorstores/dolt/dolt.go, vectorstores/dolt/dolt_test.go, vectorstores/dolt/options.go, vectorstores/mariadb/doc.go, vectorstores/mariadb/mariadb.go, vectorstores/mariadb/mariadb_test.go, vectorstores/mariadb/options.go
Add vector store implementations for MariaDB and Dolt databases, providing native vector similarity search capabilities.
- Full vector similarity search using MariaDB's native vector functions
- Support for cosine and L2 distance metrics
- Metadata filtering capabilities
- Document management (add, delete, search)
- Configurable collection names and embedding dimensions
- Git-like version control for vector data
- Same API as MariaDB implementation
- Branch and merge capabilities for vector collections
- Full compatibility with MariaDB vector functions
- Both implementations share similar architecture for consistency
- Uses testcontainers for integration testing
- Proper database initialization and table creation
- Thread-safe operations with proper connection handling
```bash
go test -v …
```
=> vectorstores: add MariaDB and Dolt vector store implementations

examples/googleai-completion-example/go.mod, examples/googleai-completion-example/googleai-completion-example.go, examples/vertex-completion-example/go.mod, examples/vertex-completion-example/vertex-completion-example.go, llms/googleai/new.go, llms/googleai/vertex/new.go, llms/openai/internal/openaiclient/chat.go
Fix memory leaks in GoogleAI/Vertex clients and goroutine leaks in OpenAI streaming responses.
- Fixes #1356 - Goroutine leak if streamingFunc returns error
- Fixes #1337 - Memory leak from creating new Gemini/Vertex clients
- Added `Close()` method to `GoogleAI` struct to properly close underlying genai client
- Added `Close()` method to `Vertex` struct to properly close underlying genai client
- Updated examples to demonstrate proper cleanup with `defer llm.Close()`
- Added context cancellation to properly terminate goroutines when errors occur
- Made channel sends non-blocking with context checks to prevent deadlocks
- Goroutine now properly exits when streaming function returns an error
The GoogleAI and Vertex clients use gRPC connections that need to be explicitly closed to prevent …
=> llms: fix memory and goroutine leaks in GoogleAI/Vertex and OpenAI streaming

llms/openai/doc.go, llms/openai/internal/openaiclient/chat.go, llms/openai/internal/openaiclient/chat_sse_test.go, llms/openai/internal/openaiclient/marshal_test.go, llms/openai/max_tokens_test.go, llms/openai/openaillm.go, llms/openai/options.go, llms/openai/options_test.go
Fixes the `max_tokens` vs `max_completion_tokens` conflict that causes OpenAI API errors.
OpenAI's API returns 400 errors when both `max_tokens` and `max_completion_tokens` are sent. The o1 models require `max_completion_tokens`, but many OpenAI-compatible providers still need `max_tokens`.
1. **MarshalJSON** ensures only one token field is sent
2. **WithMaxCompletionTokens()** - Explicit option for clarity
3. **WithLegacyMaxTokensField()** - Forces `max_tokens` for older servers
```go
// Modern OpenAI (recommended)
llm.GenerateContent(ctx, messages,
openai.WithMaxCompletionTokens(100),
)
// Legacy servers
llm.GenerateContent(ctx, messages,
llms.WithMaxTokens(100),
openai.WithLegacyMaxTokensField(),
)
```
Simpler than #1370 (380 lines vs 645+, no auto-detection magic).
Fixes issues from …
=> openai: add robust max_tokens support with backward compatibility

llms/openai/internal/openaiclient/chat.go, llms/openai/internal/openaiclient/openaiclient_test.go
Thanks for https://github.com/tmc/langchaingo/pull/1371! This is working well, but certain open AI compatible APIs have rather strict schema validation in their requests. Looking at the Digital Ocean serverless inference as an example, my requests are receiving a 400 response with the following: `request body has an error: doesn't match schema #/components/schemas/CreateChatCompletionRequest: Error at \"/metadata/openai:use_legacy_max_tokens\": value must be a string\n"}`
This filters out the "internal use" metadata from the request prior to sending it.
=> fix: filter out open ai max token metadata

vectorstores/milvus/milvus.go
The Milvus SDK at github.com/milvus-io/milvus-sdk-go/v2 was archived on March 21, 2025.
This updates the deprecation notice with:
- Specific archival date  
- Clarification that migration will require breaking changes
- Updated issue reference to #1397 for migration tracking
Updates #1397
=> vectorstores/milvus: update deprecation notice for archived SDK

documentloaders/directory.go, documentloaders/directory_test.go, documentloaders/testdata/depth/test2.md
Fix #1384 
No
RecursiveDirectoryLoader is a document loader that loads documents with allowed extensions from a directory.
RecursiveDirectoryLoader walks through a directory and its sub-directories, loading every file whose extension is on the allow-list as a document. 
```
// RecursiveDirectoryLoader is a document loader that loads documents with allowed extensions from a directory.
type RecursiveDirectoryLoader struct {
root     string
maxDepth int
allowExt map[string]struct{}
Columns []string // CSV Columns
PDFPassword string // PDF password
}
```
,See #1384
=> documentloaders: add RecursiveDirectoryLoader that loads documents with allowed extensions from a directory
